import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { findActiveBrandsForSeo, findActiveModelsForSeo } from "@/repositories/model-detail.repository";
import { modelSeoPath, toSeoSlug } from "@/lib/seo/motorcycle";
type Props={params:Promise<{brand:string}>};
async function resolveBrand(slug:string){const [brands,models]=await Promise.all([findActiveBrandsForSeo(),findActiveModelsForSeo()]);const brand=brands.find((b)=>toSeoSlug(b.brand_en)===slug);return brand?{brand,models:models.filter((m)=>m.brand_id===brand.brand_id)}:null;}
export async function generateMetadata({params}:Props):Promise<Metadata>{const p=await params;const data=await resolveBrand(p.brand);if(!data)return{title:"브랜드를 찾을 수 없음",robots:{index:false,follow:false}};const name=data.brand.brand_ko??data.brand.brand_en;return{title:name+" 오토바이 모델",description:name+"의 FitBike 등록 모델을 확인하고 모델별 연식·제원·부품 규격으로 이동하세요.",alternates:{canonical:"/motorcycles/"+p.brand}};}
export default async function BrandPage({params}:Props){const p=await params;const data=await resolveBrand(p.brand);if(!data)notFound();const name=data.brand.brand_ko??data.brand.brand_en;return <main className="mx-auto w-full max-w-5xl space-y-8 px-5 py-8 sm:py-14"><nav className="text-sm text-foreground-secondary"><Link href="/motorcycles">바이크 모델</Link></nav><header><p className="text-sm font-semibold text-primary">BRAND</p><h1 className="mt-1 text-3xl font-bold">{name} 오토바이 모델</h1><p className="mt-3 text-base leading-7 text-foreground-secondary">{name}의 등록 모델을 선택해 연식별 제원과 타이어·배터리·브레이크 규격을 확인하세요.</p></header><div className="grid gap-3 sm:grid-cols-2 md:grid-cols-3">{data.models.map((model)=><Link key={model.bike_model_id} className="rounded-xl border border-border bg-surface p-5 hover:border-primary" href={modelSeoPath(data.brand.brand_en,model.model_name_en)}><strong>{model.model_name_ko??model.model_name_en}</strong>{model.engine_cc!==null?<p className="mt-1 text-sm text-foreground-secondary">{Math.round(model.engine_cc)}cc</p>:null}</Link>)}</div></main>;}
