"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { getModelDetailProducts } from "@/features/model-detail/services/model-detail.service";
import type { ConnectedProduct, ModelDetailData, TireSpecification } from "@/features/model-detail/types/model-detail.types";

function Products({ label, items, loading, error }: { label: string; items?: ConnectedProduct[]; loading: boolean; error: boolean }) {
  const [all, setAll] = useState(false);
  if (loading) return <div aria-label={`${label} 불러오는 중`} className="h-16 animate-pulse rounded-xl bg-surface-secondary" role="status" />;
  if (error) return <p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert">상품 정보를 불러오지 못했습니다.</p>;
  if (!items?.length) return <p className="rounded-xl bg-surface-secondary p-4 text-sm text-foreground-secondary">등록된 상품이 없습니다.</p>;
  return <div className="space-y-2">{(all ? items : items.slice(0, 3)).map((item) => { const body = <><span><span className="block text-xs font-semibold text-foreground-secondary">{item.brandName}</span><span className="font-semibold">{item.productName}</span>{item.secondaryInformation ? <span className="block text-sm text-foreground-secondary">{item.secondaryInformation}</span> : null}</span>{item.detailHref ? <span aria-hidden>›</span> : null}</>; const css = "flex min-h-16 items-center justify-between rounded-xl border border-border bg-surface p-4"; return item.detailHref ? <Link aria-label={`${item.brandName} ${item.productName} 상세 보기`} className={`${css} hover:border-primary`} href={item.detailHref} key={item.id}>{body}</Link> : <div className={css} key={item.id}>{body}</div>; })}{items.length > 3 ? <button className="min-h-11 w-full rounded-xl border border-border text-sm font-semibold" onClick={() => setAll(!all)} type="button">{all ? "접기" : `${label} ${items.length - 3}개 더보기`}</button> : null}</div>;
}
function tireSize(spec: TireSpecification) { if (spec.fullSize) return spec.fullSize; if (spec.width === null || spec.diameter === null) return "규격 정보 없음"; return `${spec.width}${spec.ratio === null ? "" : `/${spec.ratio}`}-${spec.diameter}`; }
function Tire({ label, spec, items, loading, error }: { label: string; spec: TireSpecification; items?: ConnectedProduct[]; loading: boolean; error: boolean }) { return <article className="space-y-4 rounded-xl border border-border p-4"><div><h3 className="font-semibold">{label}</h3><p className="mt-1 text-xl font-bold">{tireSize(spec)}</p><p className="text-sm text-foreground-secondary">{[spec.loadIndex, spec.speedIndex, spec.tubeType].filter(Boolean).join(" · ") || "추가 규격 정보 없음"}</p></div><Products error={error} items={items} label={`${label} 상품`} loading={loading} /></article>; }

export function PartsHub({ model }: { model: ModelDetailData }) {
  const ref = useRef<HTMLElement>(null); const [enabled, setEnabled] = useState(false);
  useEffect(() => { const node = ref.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setEnabled(true); observer.disconnect(); } }, { rootMargin: "240px" }); observer.observe(node); return () => observer.disconnect(); }, []);
  const query = useQuery({ queryKey: ["model-detail-products", model.bikeModelYearId], queryFn: () => getModelDetailProducts(model.bikeModelYearId), enabled }); const loading = !enabled || query.isLoading;
  const failed = query.isError;
  return <section className="space-y-6" ref={ref}><h2 className="text-xl font-bold">이 바이크의 부품 규격</h2><section className="space-y-4 rounded-2xl border border-border bg-surface p-5"><h2 className="text-lg font-bold">타이어</h2><div className="grid gap-4 sm:grid-cols-2"><Tire error={failed} items={query.data?.tire.front} label="앞 타이어" loading={loading} spec={model.frontTire} /><Tire error={failed} items={query.data?.tire.rear} label="뒤 타이어" loading={loading} spec={model.rearTire} /></div></section><Part error={failed} label="배터리" loading={loading} products={query.data?.battery} spec={model.batteryStandardCode} sub={model.batteryVoltage} /><section className="space-y-4 rounded-2xl border border-border bg-surface p-5"><h2 className="text-lg font-bold">브레이크</h2><div className="grid gap-4 sm:grid-cols-2"><Part error={failed} label="앞 브레이크" loading={loading} products={query.data?.brake.front} spec={model.frontBrakeSpec} sub={model.frontBrakeCaliperType} nested /><Part error={failed} label="뒤 브레이크" loading={loading} products={query.data?.brake.rear} spec={model.rearBrakeSpec} sub={model.rearBrakeCaliperType} nested /></div></section></section>;
}
function Part({ label, spec, sub, products, loading, error, nested = false }: { label: string; spec: string | null; sub: string | null; products?: ConnectedProduct[]; loading: boolean; error: boolean; nested?: boolean }) { const content = <><div className="rounded-xl bg-surface-secondary p-4"><h3 className="font-semibold">{label}</h3><p className="mt-1">{spec ?? "규격 정보 없음"}</p>{sub ? <p className="text-sm text-foreground-secondary">{sub}</p> : null}</div><Products error={error} items={products} label={`${label} 상품`} loading={loading} /></>; return nested ? <div className="space-y-3">{content}</div> : <section className="space-y-4 rounded-2xl border border-border bg-surface p-5"><h2 className="text-lg font-bold">{label}</h2>{content}</section>; }
