import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const code=readFileSync(new URL('../../supabase/functions/content-pipeline-source-stage/native-resume.ts',import.meta.url),'utf8').replaceAll('export ','');
const ctx={JSON,Error};vm.runInNewContext(ts.transpile(code,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}),ctx);
const bytes=Uint8Array.from([1,2,3]),sha=createHash('sha256').update(bytes).digest('hex');
const spec={productionMethod:'NATIVE_FULL_GENERATION',prompt:'Photograph this current motorcycle only.',references:[],nativeAttemptId:'attempt',preflightOnly:true,visualMcpOperation:{workerKey:'worker'}};
const input={bucket:'content-pipeline-staging',path:`5/10/${sha}.webp`,sha256:sha,bytes:3,width:1200,height:800,persistence:{status:'READ_BACK_VERIFIED'}};
const parent={job_id:'parent',pipeline_image_id:10,contract_hash:'hash',status:'FAILED',spec,result:{generatedInput:input,checkpoint:'GENERATED_BINARY_PRESERVED'}};
const current={pipelineId:5,pipelineImageId:10,contractHash:'hash',spec:{...spec,resumeJobId:'parent'}};
const admitted={sourceJobId:'parent',sourceSha256:sha};
const execute=(c=current,p=parent,a=admitted,b=bytes)=>ctx.readStoredNativeInput(c,p,a,async path=>{assert.equal(path,input.path);return{bytes:b,mime:'image/webp'};},async data=>({sha256:createHash('sha256').update(data).digest('hex'),bytes:data.length,width:1200,height:800}));
test('server-admitted failed input reused without claiming it is staged or pixel approved',async()=>{const r=await execute();assert.deepEqual(r.bytes,bytes);assert.equal(r.mime,'image/webp');assert.equal(r.qaStatus,undefined);});
for(const [name,patch] of [['worker',{spec:{...current.spec,visualMcpOperation:{workerKey:'other'}}}],['task',{pipelineImageId:11}],['hash',{contractHash:'other'}],['prompt',{spec:{...current.spec,prompt:'Changed original scene prompt'}}],['attempt',{spec:{...current.spec,nativeAttemptId:'different'}}]])test(`${name} change rejects before Storage read`,async()=>{await assert.rejects(execute({...current,...patch}),/ACCESS_DENIED|ASSET_MISSING/);});
test('wrong source admission and finalization without reviewer QA reject failed inputs',async()=>{await assert.rejects(execute(current,parent,null),/INPUT_NOT_ADMITTED/);await assert.rejects(execute(current,parent,{...admitted,sourceJobId:'other'}),/INPUT_NOT_ADMITTED/);await assert.rejects(execute({...current,spec:{...current.spec,preflightOnly:false}}),/INPUT_NOT_ADMITTED/);});
test('semantic rejection, running jobs, missing marker and incorrect bucket reject',async()=>{await assert.rejects(execute(current,{...parent,result:{...parent.result,semanticValidation:{status:'FAIL'}}}),/ACCESS_DENIED/);await assert.rejects(execute(current,{...parent,status:'RUNNING'}),/ACCESS_DENIED/);await assert.rejects(execute(current,{...parent,result:{generatedInput:{...input,persistence:undefined}}}),/INPUT_NOT_ADMITTED/);await assert.rejects(execute(current,{...parent,result:{...parent.result,generatedInput:{...input,bucket:'public'}}}),/ASSET_MISSING/);});
test('Storage bytes and decoded dimensions must match preserved identity',async()=>{await assert.rejects(execute(current,parent,admitted,Uint8Array.from([9,9,9])),/IDENTITY_MISMATCH/);await assert.rejects(execute(current,{...parent,result:{...parent.result,generatedInput:{...input,width:390}}}),/IDENTITY_MISMATCH/);});
test('legacy server readback checkpoint is recoverable, no fake new marker needed',async()=>{const r=await execute(current,{...parent,result:{...parent.result,generatedInput:{...input,persistence:undefined}}});assert.deepEqual(r.bytes,bytes);});
