import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import test from 'node:test';
import ts from 'typescript';
import { webcrypto } from 'node:crypto';
const source=readFileSync(new URL('../../supabase/functions/content-pipeline-source-stage/generation.ts',import.meta.url),'utf8').replace(/^import .*;$/gm,'').replace(/export /g,'');
const good={productionMethod:'REFERENCE_BASED_GENERATION',prompt:'Create a clear oil filter gasket inspection photograph.',references:[{sourcePageUrl:'https://manufacturer.org/filter',sourceOwner:'Manufacturer',verifiedFacts:['The sealing gasket is on the outer base ring.'],pixelsInspected:true,checkedAt:'2026-10-02T01:00:00Z'}],transform:{maxWidth:780}};
const file={download_url:'https://files.example.org/generated.png?token=temporary',file_id:'file_native',mime_type:'image/png',file_name:'generated.png'};
function harness(download){const calls=[];const context={URL,Date,JSON,Array,String,Number,Error,Uint8Array,crypto:webcrypto,sourceUrl:v=>{const u=new URL(String(v));if(u.protocol!=='https:'||u.hostname==='localhost')throw Error('SOURCE_URL_UNSAFE');return u;},downloadSource:async url=>{calls.push(url);return typeof download==='function'?download(url):download;},fetch:()=>{throw Error('Unexpected external generation request');}};vm.runInNewContext(ts.transpile(source,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}),context);return{context,calls};}
test('native file transport never configures or calls an external model',async()=>{const h=harness();const cap=h.context.generationCapabilities();assert.equal(cap.externalGenerationApiAllowed,false);assert.equal(cap.nativeFileHandoff,true);assert.equal(cap.provider,'NONE');assert.equal(cap.requiredSettings.length,0);await assert.rejects(h.context.generateAsset(good,{}),/NATIVE_GENERATED_FILE_REQUIRED/);assert.equal(h.calls.length,0);});
test('uninspected references, arbitrary generation and unsafe file inputs are rejected',()=>{const h=harness();for(const patch of [{pixelsInspected:false},{verifiedFacts:[]},{rightsStatus:'approved'},{checkedAt:'invalid'}])assert.throws(()=>h.context.validateGenerationSpec({...good,references:[{...good.references[0],...patch}]}),/REFERENCE_EVIDENCE/);assert.throws(()=>h.context.validateGenerationSpec({...good,productionMethod:'FULL_AI_GENERATION'}),/INVALID_GENERATION/);for(const f of [{...file,file_id:''},{...file,download_url:'http://localhost/a'},{...file,mime_type:'text/html'}])assert.throws(()=>h.context.validateChatFile(f));});
test('PNG file input computes source SHA without downloading reference images or returning authorized URL',async()=>{const bytes=Uint8Array.from([137,80,78,71,13,10,26,10]);const h=harness({bytes,mime:'image/png',finalUrl:file.download_url,redirects:[file.download_url]});const r=await h.context.generateAsset({...good,chatFile:file},{});assert.deepEqual(h.calls,[file.download_url]);assert.equal(r.finalUrl,null);assert.equal(r.redirects.length,0);assert.equal(r.generation.externalApiUsed,false);assert.equal(r.generation.inputSha256,Buffer.from(await webcrypto.subtle.digest('SHA-256',bytes)).toString('hex'));assert.equal(r.imageQa,undefined);});
test('native AI edit requires attached original bytes matching inspected source URL',async()=>{const original='https://manufacturer.org/original.jpg';const inputFile={...file,download_url:'https://files.example.org/original.jpg',file_id:'file_original',mime_type:'image/jpeg'};const spec={...good,productionMethod:'REAL_SOURCE_AI_EDIT',inputAssetUrl:original,references:[{...good.references[0],sourceAssetUrl:original}],chatFile:file,inputFile};const h=harness(url=>({bytes:Uint8Array.from(url===file.download_url?[1,2]:[3,4]),mime:url===file.download_url?'image/png':'image/jpeg'}));const r=await h.context.generateAsset(spec,{});assert.equal(r.generation.referenceConditioning,'OPERATOR_ATTESTED_NATIVE_INPUT_BINARY');assert.ok(r.generation.inputSourceSha256);await assert.rejects(h.context.generateAsset({...spec,inputFile:undefined},{}),/INPUT_FILE_REQUIRED/);const mismatch=harness(url=>({bytes:Uint8Array.from(url===original?[1]:[2]),mime:url===file.download_url?'image/png':'image/jpeg'}));await assert.rejects(mismatch.context.generateAsset(spec,{}),/INPUT_IDENTITY_MISMATCH/);});
test('URL compatibility requires SHA, conflicting inputs and MIME claims fail',async()=>{const bytes=Uint8Array.from([1,2,3]);const h=harness({bytes,mime:'image/png'});await assert.rejects(h.context.generateAsset({...good,chatFile:{...file,mime_type:'image/jpeg'}},{}),/MIME_MISMATCH/);await assert.rejects(h.context.generateAsset({...good,generatedAssetUrl:'https://files.example.org/a',expectedGeneratedSha:'a'.repeat(64)},{}),/IDENTITY_MISMATCH/);assert.throws(()=>h.context.validateGenerationSpec({...good,chatFile:file,generatedAssetUrl:file.download_url,expectedGeneratedSha:'a'.repeat(64)}),/MULTIPLE_GENERATED_INPUTS/);assert.throws(()=>h.context.validateGenerationSpec({...good,chatFile:file,resumeJobId:'1'.repeat(36)}),/INVALID_GENERATION_RESUME/);});

test('native file with optional SHA accepts matching bytes and rejects mismatches',async()=>{const bytes=Uint8Array.from([1,2,3]);const sha=Buffer.from(await webcrypto.subtle.digest('SHA-256',bytes)).toString('hex');const h=harness({bytes,mime:'image/png'});const r=await h.context.generateAsset({...good,chatFile:file,expectedGeneratedSha:sha},{});assert.equal(r.generation.inputSha256,sha);await assert.rejects(h.context.generateAsset({...good,chatFile:file,expectedGeneratedSha:'a'.repeat(64)},{}),/IDENTITY_MISMATCH/);assert.throws(()=>h.context.validateGenerationSpec({...good,chatFile:file,expectedGeneratedSha:'bad'}),/SHA_REQUIRED/);assert.throws(()=>h.context.validateGenerationSpec({...good,expectedGeneratedSha:sha}),/URL_REQUIRED/);});

test('native full generation permits no references and never invents reference conditioning',async()=>{
 const bytes=Uint8Array.from([1,2,3]);const h=harness({bytes,mime:'image/png'});
 const spec={...good,productionMethod:'NATIVE_FULL_GENERATION',references:[],chatFile:file};
 const result=await h.context.generateAsset(spec);
 assert.deepEqual(h.calls,[file.download_url]);assert.equal(result.generation.referenceConditioning,'NONE_CURRENT_TASK_SCENE');assert.equal(result.generation.externalApiUsed,false);
 assert.ok(h.context.generationCapabilities().nativeProductionMethods.includes('NATIVE_FULL_GENERATION'));
 for(const extra of [{references:good.references},{inputAssetUrl:'https://manufacturer.org/input.jpg'},{inputFile:file}])assert.throws(()=>h.context.validateGenerationSpec({...spec,...extra}));
 for(const method of ['REFERENCE_BASED_GENERATION','REAL_SOURCE_AI_EDIT'])assert.throws(()=>h.context.validateGenerationSpec({...spec,productionMethod:method}),/INVALID_GENERATION_SPEC/);
});


test('both Edge capabilities declare the deployed visual Contract and common policy versions',()=>{
 const h=harness();const cap=h.context.generationCapabilities();
 assert.equal(JSON.stringify(cap.visualContractVersions),JSON.stringify([4,5]));assert.equal(cap.visualPolicyVersion,'VISUAL_COMMON_V1');
 const mcpSource=readFileSync(new URL('../../supabase/functions/content-pipeline-visual-mcp/generation.ts',import.meta.url),'utf8').replace(/^import .*;$/gm,'').replace(/export /g,'');
 const mcp={URL,Date,JSON,Array,String,Number,Error,sourceUrl:h.context.sourceUrl};vm.runInNewContext(ts.transpile(mcpSource,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}),mcp);
 const mcpCap=mcp.generationCapabilities();
 for(const field of ['visualContractVersions','visualPolicyVersion','nativeProductionMethods'])assert.equal(JSON.stringify(mcpCap[field]),JSON.stringify(cap[field]));
 assert.equal(mcpCap.serverGenerationSupported,false);assert.equal(mcpCap.externalGenerationApiAllowed,false);
});
