import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import test from 'node:test';
import ts from 'typescript';
import { webcrypto } from 'node:crypto';
const source=readFileSync(new URL('../../supabase/functions/content-pipeline-source-stage/generation.ts',import.meta.url),'utf8').replace(/^import .*;$/gm,'').replace(/export /g,'');
const good={productionMethod:'REFERENCE_BASED_GENERATION',prompt:'Create a clear oil filter gasket inspection photograph.',references:[{sourcePageUrl:'https://manufacturer.org/filter',sourceOwner:'Manufacturer',verifiedFacts:['The sealing gasket is on the outer base ring.'],pixelsInspected:true,checkedAt:'2026-10-02T01:00:00Z'}],transform:{maxWidth:780}};
function harness({fetchImpl,download,env={}}={}) {
 const calls=[];
 const context={URL,Date,JSON,Array,String,Number,Error,Uint8Array,TextDecoder,AbortSignal,FormData,Blob,crypto:webcrypto,atob,sourceUrl:v=>{const u=new URL(String(v));if(u.protocol!=='https:'||u.hostname==='localhost')throw Error('SOURCE_URL_UNSAFE');return u;},downloadSource:async url=>{calls.push({download:url});return download;},verifySourceSignature:(b,m)=>{if(new TextDecoder().decode(b.subarray(0,4))!=='RIFF'||new TextDecoder().decode(b.subarray(8,12))!=='WEBP'||m!=='image/webp')throw Error('SOURCE_SIGNATURE_INVALID');},fetch:async(url,options)=>{calls.push({url,options});return fetchImpl(url,options);},Deno:{env:{get:k=>env[k]}}};
 vm.runInNewContext(ts.transpile(source,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}),context);
 return {context,calls};
}
const configured={FITBIKE_IMAGE_GENERATION_ENABLED:'true',OPENAI_API_KEY:'test-secret',FITBIKE_IMAGE_MODEL:'gpt-image-2.5-sunburst'};
test('configuration is explicit and no provider request occurs without it',async()=>{const h=harness();const cap=h.context.generationCapabilities(()=>undefined);assert.equal(cap.referenceBasedGeneration,false);assert.equal(cap.generatedAssetUrlHandoff,true);assert.equal(cap.chatImagegenBinaryBridge,false);await assert.rejects(h.context.generateAsset(good,{}),/PROVIDER_NOT_CONFIGURED/);assert.equal(h.calls.length,0);});
test('references require actual pixel and factual evidence; no rights status fields',()=>{const h=harness();for(const patch of [{pixelsInspected:false},{verifiedFacts:[]},{rightsStatus:'approved'},{checkedAt:'invalid'}]){assert.throws(()=>h.context.validateGenerationSpec({...good,references:[{...good.references[0],...patch}]}),/REFERENCE_EVIDENCE/);}assert.throws(()=>h.context.validateGenerationSpec({...good,productionMethod:'FULL_AI_GENERATION'}),/INVALID_GENERATION/);});
test('generation uses facts without downloading the reference asset and returns actual provider bytes',async()=>{const webp=Buffer.from('RIFFxxxxWEBPpayload');const h=harness({env:configured,fetchImpl:async()=>new Response(JSON.stringify({data:[{b64_json:webp.toString('base64')}],usage:{output_tokens:3}}),{headers:{'x-request-id':'provider-123'}})});const r=await h.context.generateAsset(good,{must_show:['sealing gasket']});assert.deepEqual(Buffer.from(r.bytes),webp);assert.equal(h.calls.length,1);const req=JSON.parse(h.calls[0].options.body);assert.equal(req.n,1);assert.equal(req.output_format,'webp');assert.match(req.prompt,/sealing gasket/);assert.equal(r.generation.providerRequestId,'provider-123');assert.equal(r.generation.productionMethod,'REFERENCE_BASED_GENERATION');});
test('AI edit uses exact downloaded image input; mismatched evidence is rejected',async()=>{const webp=Buffer.from('RIFFxxxxWEBPpayload');const input='https://manufacturer.org/photo.jpg';const spec={...good,productionMethod:'REAL_SOURCE_AI_EDIT',inputAssetUrl:input,references:[{...good.references[0],sourceAssetUrl:input}]};const h=harness({env:configured,download:{bytes:Uint8Array.from([255,216,255,0]),mime:'image/jpeg'},fetchImpl:async()=>new Response(JSON.stringify({data:[{b64_json:webp.toString('base64')}]}))});await h.context.generateAsset(spec,{});assert.equal(h.calls[0].download,input);assert.equal(h.calls[1].url,'https://api.openai.com/v1/images/edits');assert.ok(h.calls[1].options.body.get('image[]'));assert.throws(()=>h.context.validateGenerationSpec({...spec,inputAssetUrl:'https://other.org/a.jpg'}),/INPUT_REFERENCE/);});
test('external generated asset is verified by SHA without any provider request',async()=>{const bytes=Uint8Array.from(Buffer.from('RIFFxxxxWEBPpayload'));const sha=Buffer.from(await webcrypto.subtle.digest('SHA-256',bytes)).toString('hex');const h=harness({download:{bytes,mime:'image/webp',finalUrl:'https://assets.org/out.webp',redirects:[]}});const spec={...good,generatedAssetUrl:'https://assets.org/out.webp',expectedGeneratedSha:sha};const r=await h.context.generateAsset(spec,{});assert.equal(r.generation.transport,'GENERATED_ASSET_URL');await assert.rejects(h.context.generateAsset({...spec,expectedGeneratedSha:'a'.repeat(64)},{}),/IDENTITY_MISMATCH/);assert.equal(h.calls.some(c=>c.url),false);});
test('provider HTTP errors are sanitized and no fake binary or QA is returned',async()=>{const h=harness({env:configured,fetchImpl:async()=>new Response('secret error',{status:401})});await assert.rejects(h.context.generateAsset(good,{}),/GENERATION_PROVIDER_HTTP_401/);assert.equal(h.calls.length,1);});
