import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
import assert from 'node:assert/strict';
import ts from 'typescript';
const source=readFileSync(new URL('../../supabase/functions/content-pipeline-source-stage/index.ts',import.meta.url),'utf8').replace(/^import[\s\S]*?;\n/gm,'');
const JOB='11111111-1111-4111-8111-111111111111';
function harness({mode='generation',failFinal=false,late=false,resume=false,resumeMismatch=false}={}){
 let handler;const objects=new Map(),updates=[],calls=[];
 const spec=mode==='generation'?{productionMethod:'REFERENCE_BASED_GENERATION',prompt:'verified composition',references:[{sourcePageUrl:'https://maker.org/a'}],transform:{}}:{sourceAssetUrl:'https://maker.org/a.jpg',sourcePageUrl:'https://maker.org/a',sourceOwner:'Maker',transform:{}};
 if(resume){spec.productionMethod='REAL_SOURCE_AI_EDIT';spec.resumeJobId=JOB;spec.inputAssetUrl=resumeMismatch?'https://maker.org/b.jpg':'https://maker.org/a.jpg';}
 const input=Uint8Array.from(Buffer.from('RIFFxxxxWEBPinput')),final=Uint8Array.from(Buffer.from('RIFFxxxxWEBPfinalpixels'));
 const proof=b=>({sha256:b.length===input.length?'a'.repeat(64):'b'.repeat(64),bytes:b.length,mime:'image/webp',width:780,height:585,decode:'PASS'});
 const sb={rpc:async(name)=>{calls.push(name);return {data:name.includes('consume')?{pipelineId:26,pipelineImageId:2009,contractHash:'hash',spec}:true,error:null};},from:()=>({select:cols=>({eq:()=>({single:async()=>({data:cols.includes('pipeline_image_id,contract_hash')?{pipeline_image_id:2009,contract_hash:'hash',spec:{...spec,inputAssetUrl:'https://maker.org/a.jpg'},result:{generatedInput:{bucket:'content-pipeline-staging',path:'26/2009/'+ 'a'.repeat(64)+'.webp',sha256:'a'.repeat(64),bytes:input.length},generation:{provider:'TEST',inputSourceSha256:'c'.repeat(64)}}}:{generation_contract:{source_strategy:'REFERENCE_FIRST_GENERATIVE'},generation_contract_hash:'hash'},error:null})})}),update:record=>{updates.push(record);const q={eq:()=>q,select:()=>q,maybeSingle:async()=>({data:late?null:{job_id:JOB},error:null}),then:resolve=>resolve({error:null})};return q;},delete:()=>({eq:async()=>({error:null})}),insert:async()=>({error:null})}),storage:{from:()=>({download:async path=>({data:objects.has(path)?new Blob([objects.get(path)],{type:'image/webp'}):null,error:objects.has(path)?null:{message:'missing'}}),upload:async(path,b)=>{if(failFinal&&path.includes('b'.repeat(64)))return {error:{message:'failed'}};objects.set(path,Uint8Array.from(b));return {error:null};},createSignedUrl:async()=>({data:{signedUrl:'https://private.org/exact'},error:null})})}};
 if(resume)objects.set('26/2009/'+ 'a'.repeat(64)+'.webp',input);
 const context={createClient:()=>sb,Deno:{env:{get:()=>''},serve:fn=>handler=fn},Response,TextDecoder,Uint8Array,Date,JSON,Boolean,Number,Error,String,Array,btoa,sourceUrl:u=>new URL(u),validateTransform:t=>t,downloadSource:async()=>{calls.push('downloadOriginal');return {bytes:input,mime:'image/webp',finalUrl:'https://maker.org/a',redirects:[]};},generateAsset:async()=>{calls.push('generate');return{bytes:input,mime:'image/webp',finalUrl:null,redirects:[],generation:{provider:'TEST',inputSourceSha256:null}};},generationCapabilities:()=>({providerConfigured:false}),transformSource:async()=>({webp:final,width:780,height:585}),inspectWebp:async b=>proof(b),sha256:async b=>proof(b).sha256};
 vm.runInNewContext(ts.transpile(source,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}),context);
 return{objects,updates,calls,run:()=>handler(new Request('https://stage.org',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jobId:JOB})}))};
}
test('generated binary is preserved before conversion and exact Final is STAGED with pending semantic QA',async()=>{const h=harness();const res=await h.run();assert.equal(res.status,200);assert.deepEqual(h.calls,['content_pipeline_consume_source_stage_ticket_v1','content_pipeline_reference_generation_allowed_v1','generate']);assert.equal(h.objects.size,2);assert.equal(h.updates[0].result.checkpoint,'GENERATED_BINARY_PRESERVED');const staged=h.updates.at(-1);assert.equal(staged.status,'STAGED');assert.equal(staged.result.generatedInput.sha256,'a'.repeat(64));assert.equal(staged.result.sha256,'b'.repeat(64));assert.equal(staged.result.imageQa,'PENDING');assert.equal(staged.result.aiGenerationApplied,true);assert.equal(staged.result.provenance.sourceAssetUrl,null);});
test('Final staging failure preserves generated input and reports actual FAILED without fake QA',async()=>{const h=harness({failFinal:true});const res=await h.run();assert.equal(res.status,422);assert.equal((await res.json()).error,'STAGING_UPLOAD_FAILED');assert.equal(h.objects.size,1);assert.equal(h.updates[0].result.checkpoint,'GENERATED_BINARY_PRESERVED');assert.equal(h.updates.at(-1).status,'FAILED');assert.equal(h.updates.some(u=>u.status==='STAGED'),false);});
test('late fenced checkpoint cannot become STAGED',async()=>{const h=harness({late:true});const res=await h.run();assert.equal(res.status,422);assert.equal((await res.json()).error,'GENERATED_BINARY_RECEIPT_SAVE_FAILED');assert.equal(h.updates.some(u=>u.status==='STAGED'),false);});
test('original direct-source path still downloads and stages without generation',async()=>{const h=harness({mode:'source'});const res=await h.run();assert.equal(res.status,200);assert.ok(h.calls.includes('downloadOriginal'));assert.equal(h.calls.includes('generate'),false);assert.equal(h.updates.at(-1).result.provenance.sourceAssetUrl,'https://maker.org/a.jpg');});

test('resume reuses preserved provider binary without generation and rejects relabeling a different input photo',async()=>{const h=harness({resume:true});const res=await h.run();assert.equal(res.status,200);assert.equal(h.calls.includes('generate'),false);assert.equal(h.updates.at(-1).result.provenance.sourceAssetUrl,'https://maker.org/a.jpg');const bad=harness({resume:true,resumeMismatch:true});const failed=await bad.run();assert.equal(failed.status,422);assert.equal((await failed.json()).error,'GENERATION_RESUME_ACCESS_DENIED');assert.equal(bad.updates.some(u=>u.status==='STAGED'),false);});
