import { readFileSync } from "node:fs";
import vm from "node:vm";
import assert from "node:assert/strict";
import test from "node:test";
import ts from "typescript";
const source=readFileSync(new URL("../../supabase/functions/content-pipeline-visual-mcp/index.ts",import.meta.url),"utf8").replace(/^import .*;$/gm,"").replaceAll('await import("./generation.ts")','await loadGeneration()').replace('e instanceof Error?e.message:"VISUAL_OPERATION_FAILED"','String(e.message ?? e)');
const REQUEST="11111111-1111-4111-8111-111111111111",JOB="22222222-2222-4222-8222-222222222222";
function harness({email="operator@example.org",confirmed=true,configured=true,active=true,jobImage=2000,role="BODY",duplicate=false,provider=false}={}){
 let handler;const calls=[];
 const current={activeClaim:active,status:active?"PROCESSING":"RETRY",claim:{pipelineImageId:2000,pipelineId:21,pipelineImageRunId:3,claimToken:REQUEST,generationContractHash:"contract",generationContract:{asset_role:role}}};
 const sb={auth:{getUser:async token=>token==="valid"?{data:{user:{id:"user",email,email_confirmed_at:confirmed?"now":null}},error:null}:{data:{user:null},error:{message:"bad"}}},rpc:async(name,args)=>{calls.push({name,args});if(name.includes("request_status"))return {data:current,error:null};if(name.includes("approve_source_stage")){current.status="READY_FOR_UPLOAD";return {data:{},error:null};}if(name.includes("fail_image")){current.activeClaim=false;current.status=args.p_failure_status;return {data:{},error:null};}return{data:{jobId:JOB},error:null};},from:()=>({select:()=>({in:()=>({neq:()=>({eq:()=>({limit:async()=>({data:duplicate?[{pipeline_image_id:2003,status:"DONE"}]:[],error:null})})})}),eq:()=>({maybeSingle:async()=>({data:{pipeline_image_id:jobImage,contract_hash:"contract",status:"STAGED",result:{}}}),single:async()=>({data:{status:current.status,handoff_phase:current.status==="READY_FOR_UPLOAD"?"READY_FOR_UPLOAD":"PRODUCING",staging_asset:current.status==="READY_FOR_UPLOAD"?{sha256:"a".repeat(64)}:null},error:null})})})})};
 const context={sourceUrl:value=>{const u=new URL(String(value));if(u.protocol!=="https:")throw Error("SOURCE_URL_UNSAFE");return u;},Date,createClient:()=>sb,Deno:{env:{get:key=>key==="FITBIKE_IMAGE_GENERATION_ENABLED"?(provider?"true":"false"):key==="OPENAI_API_KEY"?(provider?"test-key":""):key==="FITBIKE_IMAGE_MODEL"?(provider?"gpt-image-2.5-sunburst":""):key==="CONTENT_FACTORY_MCP_OPERATOR_EMAILS"?(configured?"operator@example.org":""):"https://example.supabase.co"},serve:fn=>{handler=fn;}},Request,Response,URL,TextEncoder,Uint8Array,Array,Number,JSON,String,Error,btoa};
 const generation=readFileSync(new URL("../../supabase/functions/content-pipeline-visual-mcp/generation.ts",import.meta.url),"utf8").replace(/^import .*;$/gm,"").replace(/export /g,"");
 vm.runInNewContext(ts.transpile(generation,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}),context);
 context.loadGeneration=async()=>({validateGenerationSpec:context.validateGenerationSpec,generationCapabilities:context.generationCapabilities});
 vm.runInNewContext(ts.transpile(source,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}),context);
 return {calls,send:async(method="tools/list",args={},name,token="valid",body)=>handler(new Request("https://example.supabase.co/functions/v1/content-pipeline-visual-mcp",{method:"POST",headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})},body:body??JSON.stringify({jsonrpc:"2.0",id:1,method,params:{name,arguments:args}})}))};
}
test("authentication blocks anonymous, invalid, unconfigured and unapproved users",async()=>{for(const [options,token,status] of [[{},"",401],[{},"bad",401],[{configured:false},"valid",503],[{email:"other@example.org"},"valid",403],[{confirmed:false},"valid",403]]){const h=harness(options);assert.equal((await h.send("ping",{},null,token)).status,status);assert.equal(h.calls.length,0);}});
test("null and arrays are rejected before JSON-RPC access",async()=>{for(const body of ["null","[]"]){assert.equal((await harness().send("ping",{},null,"valid",body)).status,400);}});
test("tool list includes the complete 3-A boundaries with truthful annotations",async()=>{const b=await(await harness().send()).json();assert.equal(b.result.tools.length,13);assert.equal(b.result.tools.find(t=>t.name==="inspect_visual_source").annotations.readOnlyHint,true);assert.equal(b.result.tools.find(t=>t.name==="dispatch_visual_source").annotations.openWorldHint,true);});
test("valid source delegates only bounded named dispatch with server-owned worker",async()=>{const h=harness();const b=await(await h.send("tools/call",{requestId:REQUEST,operationId:JOB,spec:{sourceAssetUrl:"https://photos.example.org/image.jpg",sourcePageUrl:"https://photos.example.org/page",sourceOwner:"Manufacturer",transform:{maxWidth:780,annotations:[{type:"circle",x:.5,y:.5,radius:.1}]}}},"dispatch_visual_source")).json();assert.equal(b.result.isError,undefined);const call=h.calls.at(-1);assert.equal(call.name,"content_pipeline_dispatch_visual_source_request_v1");assert.equal(call.args.p_worker_key,"mcp-3a-user");});
test("invalid transform/rights fields and inactive claim never dispatch",async()=>{for(const [options,extra] of [[{}, {circle:{x:.5,y:.5,radius:.1}}],[{active:false},{}]]){const h=harness(options);const b=await(await h.send("tools/call",{requestId:REQUEST,operationId:JOB,spec:{sourceAssetUrl:"https://photos.example.org/image.jpg",sourcePageUrl:"https://photos.example.org/page",sourceOwner:"Manufacturer",transform:extra}},"dispatch_visual_source")).json();assert.equal(b.result.isError,true);assert.equal(h.calls.some(c=>c.name.includes("dispatch")),false);}});
test("cross-image inspection is rejected before storage download",async()=>{const h=harness({jobImage:2001});const b=await(await h.send("tools/call",{requestId:REQUEST,jobId:JOB},"inspect_visual_source")).json();assert.equal(b.result.isError,true);assert.match(b.result.content[0].text,/ACCESS_DENIED/);});
test("failure closure re-reads the receipt and never completes",async()=>{const h=harness();const b=await(await h.send("tools/call",{requestId:REQUEST,status:"RETRY",stage:"SOURCE",code:"DOWNLOAD_FAILED",error:"source unavailable"},"fail_visual_image")).json();assert.equal(b.result.structuredContent.status,"RETRY");assert.equal(b.result.structuredContent.activeClaim,false);assert.equal(h.calls.at(-1).name,"content_pipeline_visual_claim_request_status_v1");assert.equal(h.calls.some(c=>c.name.includes("complete")),false);});
test("closed claim cannot authorize source dispatch",async()=>{const h=harness({active:false});await h.send("tools/call",{requestId:REQUEST,operationId:JOB,spec:{}},"dispatch_visual_source");assert.equal(h.calls.length,1);});

const baseQa={contractHash:"contract",imageQa:"PASS",mobileQa:"PASS",imageSeoQa:"PASS"};
test("approval schema exposes exact role QA fields without prohibiting evidence",async()=>{const b=await(await harness().send()).json();const q=b.result.tools.find(t=>t.name==="approve_visual_source").inputSchema.properties.qa;assert.deepEqual(q.required,Object.keys(baseQa));for(const k of ["representativeImageQa","cardCropQa","heroCropQa"])assert.deepEqual(q.properties[k].enum,["PASS"]);assert.equal(q.additionalProperties,true);});
test("role approval reports every missing field before mutation",async()=>{for(const [role,missing] of [["BODY",[]],["THUMBNAIL",["representativeImageQa","cardCropQa"]],["HERO",["representativeImageQa","heroCropQa"]],["THUMBNAIL_HERO",["representativeImageQa","cardCropQa","heroCropQa"]]]){const h=harness({role});const b=await(await h.send("tools/call",{requestId:REQUEST,jobId:JOB,expectedSha:"a".repeat(64),qa:{...baseQa,representative:{status:"PASS"}}},"approve_visual_source")).json();if(missing.length){assert.equal(b.result.isError,true);for(const k of missing)assert.ok(b.result.content[0].text.includes(k));assert.equal(h.calls.some(c=>c.name.includes("approve_source_stage")),false);}else assert.equal(b.result.structuredContent.status,"READY_FOR_UPLOAD");}});
test("hero approval forwards inspected QA and evidence unchanged; rejects mismatch and non-PASS",async()=>{const qa={...baseQa,representativeImageQa:"PASS",cardCropQa:"PASS",heroCropQa:"PASS",evidence:"inspected service crops"};const h=harness({role:"THUMBNAIL_HERO"});const b=await(await h.send("tools/call",{requestId:REQUEST,jobId:JOB,expectedSha:"a".repeat(64),qa},"approve_visual_source")).json();assert.equal(b.result.structuredContent.status,"READY_FOR_UPLOAD");assert.deepEqual(h.calls.find(c=>c.name.includes("approve_source_stage")).args.p_qa,qa);for(const change of [{contractHash:"other"},{heroCropQa:"FAIL"}]){const x=harness({role:"THUMBNAIL_HERO"});const bad=await(await x.send("tools/call",{requestId:REQUEST,jobId:JOB,expectedSha:"a".repeat(64),qa:{...qa,...change}},"approve_visual_source")).json();assert.equal(bad.result.isError,true);assert.equal(x.calls.some(c=>c.name.includes("approve_source_stage")),false);}});

test("source usage is readonly and duplicate dispatch stops before creating a job",async()=>{const args={requestId:REQUEST,sourceAssetUrl:"https://photos.example.org/image.jpg"};for(const duplicate of [false,true]){const h=harness({duplicate});const b=await(await h.send("tools/call",args,"check_visual_source_usage")).json();assert.equal(b.result.structuredContent.result,duplicate?"DUPLICATE":"NO_KNOWN_DUPLICATE");assert.equal(b.result.structuredContent.identityScope,"EXACT_URL_ONLY");assert.equal(h.calls.length,1);}const h=harness({duplicate:true});const b=await(await h.send("tools/call",{requestId:REQUEST,operationId:JOB,spec:{sourceAssetUrl:args.sourceAssetUrl,sourcePageUrl:"https://photos.example.org/page",sourceOwner:"Manufacturer",transform:{}}},"dispatch_visual_source")).json();assert.equal(b.result.isError,true);assert.match(b.result.content[0].text,/DUPLICATE_SOURCE_PREFLIGHT/);assert.equal(h.calls.some(c=>c.name.includes("dispatch")),false);});

test("usage requires receipt and validates source SHA; clear is never QA PASS",async()=>{for(const extra of [{sourceSha256:"bad"},{sourceAssetUrl:"http://photos.example.org/a"}]){const h=harness();const b=await(await h.send("tools/call",{requestId:REQUEST,sourceAssetUrl:"https://photos.example.org/a",...extra},"check_visual_source_usage")).json();assert.equal(b.result.isError,true);}const h=harness();const b=await(await h.send("tools/call",{requestId:REQUEST,sourceAssetUrl:"https://photos.example.org/a",sourceSha256:"b".repeat(64)},"check_visual_source_usage")).json();assert.equal(b.result.structuredContent.identityScope,"URL_AND_SOURCE_SHA256");assert.equal(b.result.structuredContent.finalApprovalGateRequired,true);assert.equal(b.result.structuredContent.imageQa,undefined);});

test("maintenance status is read-only and needs no image Claim",async()=>{const h=harness({active:false});const b=await(await h.send("tools/call",{},"get_visual_maintenance_status")).json();assert.equal(b.result.isError,undefined);assert.equal(h.calls.length,1);assert.equal(h.calls[0].name,"content_pipeline_staging_maintenance_status_v1");});

const generationSpec={productionMethod:"REFERENCE_BASED_GENERATION",prompt:"Create a verified oil filter gasket photograph.",references:[{sourcePageUrl:"https://manufacturer.org/filter",sourceOwner:"Manufacturer",verifiedFacts:["Sealing gasket is on the filter base."],pixelsInspected:true,checkedAt:"2026-10-02T01:00:00Z"}],transform:{maxWidth:780}};
test("generation capability preflight is readonly, requires no Claim and returns no credentials",async()=>{for(const provider of [false,true]){const h=harness({provider,active:false});const b=await(await h.send("tools/call",{},"get_visual_generation_capabilities")).json();assert.equal(b.result.structuredContent.providerConfigured,provider);assert.equal(h.calls.length,0);assert.equal(JSON.stringify(b).includes("test-key"),false);}});
test("generation dispatch checks capability and active claim before named RPC",async()=>{for(const [options,expected] of [[{provider:true},true],[{provider:false},false],[{provider:true,active:false},false]]){const h=harness(options);const b=await(await h.send("tools/call",{requestId:REQUEST,operationId:JOB,spec:generationSpec},"dispatch_visual_generation")).json();assert.equal(h.calls.some(c=>c.name==="content_pipeline_dispatch_visual_generation_request_v1"),expected);if(expected){assert.equal(b.result.isError,undefined);assert.deepEqual(h.calls.at(-1).args.p_spec,generationSpec);}else assert.equal(b.result.isError,true);}});
