import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import test from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
const sha=async b=>Buffer.from(await webcrypto.subtle.digest('SHA-256',b)).toString('hex');
const code=readFileSync(new URL('../../supabase/functions/content-pipeline-source-stage/source-resume.ts',import.meta.url),'utf8').replace(/^import type .*;\n/gm,'').replaceAll('export ','');
const ctx={Uint8Array,JSON,Error};vm.runInNewContext(ts.transpile(code,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}),ctx);
const bytes=Uint8Array.from([1,2,3]);const canonical=await sha(bytes),original='a'.repeat(64);
const spec={sourceAssetUrl:'https://official.example/manual.pdf',sourcePageUrl:'https://official.example/page',sourceOwner:'Official',sourcePdfPage:79,transform:{maxWidth:780,crop:{x:.2,y:.2,width:.5,height:.5}},visualMcpOperation:{workerKey:'worker'}};
const previous={job_id:'parent',pipeline_id:5,pipeline_image_id:10,contract_hash:'hash',status:'STAGED',spec:{...spec,preflightOnly:true},result:{bucket:'content-pipeline-staging',path:`5/10/${canonical}.webp`,sha256:canonical,bytes:3,width:780,height:500,decode:'PASS',storageVerification:'PASS',preflightOnly:true,preStagingSourceSha256:original,provenance:{sourceMime:'application/pdf',sourceSha256:original,sourcePdfPage:79}}};
const current={pipelineId:5,pipelineImageId:10,contractHash:'hash',spec:{...spec,preStagingQa:{sourceJobId:'parent',sourceSha256:original},transform:{...spec.transform,annotations:[{type:'circle',x:.5,y:.5,radius:.1}]}}};
const inspect=async b=>({sha256:await sha(b),bytes:b.length,width:780,height:500});
const execute=(c=current,p=previous,data=bytes)=>ctx.readStoredSourceCandidate(c,p,async path=>{assert.equal(path,previous.result.path);return{bytes:data,mime:'image/webp'};},inspect);
test('stored PDF candidate reuses exact canonical bytes and original attestation identity without network',async()=>{const r=await execute();assert.deepEqual(r.bytes,bytes);assert.equal(r.sourceSha256,original);assert.equal(r.canonicalSha256,canonical);assert.equal(r.provenance.sourceMime,'application/pdf');});
for(const [name,patch] of [['worker',{spec:{...current.spec,visualMcpOperation:{workerKey:'other'}}}],['task',{pipelineImageId:11}],['contract',{contractHash:'other'}],['pipeline',{pipelineId:6}]])test(`cross ${name} rejected before stored byte access`,async()=>{await assert.rejects(execute({...current,...patch}),/SOURCE_RESUME_ACCESS_DENIED/);});
test('changed crop or width rejected, not reapplied to already cropped canonical',async()=>{for(const transform of [{...spec.transform,maxWidth:390},{...spec.transform,crop:{...spec.transform.crop,x:.1}}])await assert.rejects(execute({...current,spec:{...current.spec,transform}}),/BASE_TRANSFORM_CHANGED/);});
test('tampered stored bytes rejected against canonical SHA',async()=>{await assert.rejects(execute(current,previous,Uint8Array.from([9,9,9])),/CANONICAL_IDENTITY_MISMATCH/);});
test('wrong source SHA, page, invalidated candidate and annotated parent rejected',async()=>{await assert.rejects(execute({...current,spec:{...current.spec,preStagingQa:{sourceJobId:'parent',sourceSha256:canonical}}}),/SOURCE_IDENTITY_MISMATCH/);await assert.rejects(execute({...current,spec:{...current.spec,sourcePdfPage:80}}),/PROVENANCE_MISMATCH/);await assert.rejects(execute(current,{...previous,result:{...previous.result,semanticValidation:{status:'FAIL'}}}),/ACCESS_DENIED/);await assert.rejects(execute(current,{...previous,result:{...previous.result,annotationApplied:true}}),/BASE_TRANSFORM_CHANGED/);});

test('worker promotes stored raster without downloader or PDF renderer and passes original SHA to gate',async()=>{
 let harness=readFileSync(new URL('./visual-pre-staging-worker.test.mjs',import.meta.url),'utf8').split('const source={')[0].replace(/^import.*;\n/,'');
 harness=harness.replace('const ctx={Deno:', 'const ctx={readStoredSourceCandidate:resume,Deno:');
 harness=harness.replace('if(previous?.result?.generatedInput)', 'if(previous?.result?.path)map.set(previous.result.path,new Blob([storedBytes],{type:"image/webp"}));\n if(previous?.result?.generatedInput)');
 harness=harness.replace("{generation_contract:{},generation_contract_hash:'hash'}", "{pipeline_id:5,generation_contract:{},generation_contract_hash:'hash',visual_phase:'REVIEWING',review_candidate:{jobId:'parent'}}");
 harness=harness.replace("if(name==='content_pipeline_pre_staging_gate_v1')", "if(name==='content_pipeline_review_candidate_v1')return{data:{contractHash:'hash'},error:null};if(name==='content_pipeline_pre_staging_gate_v1')");
 harness=harness.replace('downloadSource:async()=>({', 'downloadSource:async()=>{throw Error("UNEXPECTED_EXTERNAL_FETCH");return({').replace("redirects:[]}),generateAsset", "redirects:[]});},generateAsset");
 harness=harness.replaceAll('import.meta.url',JSON.stringify(import.meta.url));
 harness=harness.replace("select:()=>chain(table)", "select:columns=>{ if(table==='27_content_pipeline_source_stage_job') assert.ok(!columns.split(',').includes('pipeline_id'),'source Job has no pipeline_id column'); return chain(table); }");
 harness+='\n globalThis.executeWorker=execute;';
 const h={Buffer,URL,readFileSync,vm,ts,webcrypto,test,assert,Request,Response,Blob,Uint8Array,Date,JSON,Array,Number,String,Error,Math,Map,btoa,atob,resume:ctx.readStoredSourceCandidate,storedBytes:bytes};
 vm.runInNewContext(harness,h);
 const p=await h.executeWorker({spec:current.spec,gate:'PASS',previous});
 assert.equal(p.status,200,JSON.stringify(p.body));
 assert.equal(p.result.preStagingSourceSha256,original);
 assert.equal(p.result.provenance.sourceMime,'application/pdf');
 assert.equal(p.calls.find(x=>x.name==='content_pipeline_pre_staging_gate_v1').args.p_source_sha,original);
 assert.equal(p.calls.find(x=>x.name==='transform').annotations.length,1);
});
