begin;

create table public."16_content_topic" (
  content_topic_id bigint generated by default as identity primary key,
  topic_key text not null unique,
  topic text not null,
  content_type text not null,
  part_type text,
  bike_model_id bigint,
  normalized_subject text not null,
  normalized_action text not null,
  normalized_scope text not null,
  status text not null default 'PLANNED',
  priority integer not null default 2,
  content_id bigint,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint "16_content_topic_content_type_check" check (
    content_type = any (array['MAINTENANCE'::text, 'DIY'::text, 'PARTS_GUIDE'::text, 'MODEL_GUIDE'::text])
  ),
  constraint "16_content_topic_part_type_check" check (
    part_type is null or part_type = any (array['TIRE'::text, 'BATTERY'::text, 'BRAKE'::text])
  ),
  constraint "16_content_topic_scope_check" check (
    normalized_scope = any (array['GENERIC'::text, 'MODEL'::text])
  ),
  constraint "16_content_topic_status_check" check (
    status = any (array['PLANNED'::text, 'GENERATING'::text, 'REVIEW_REQUIRED'::text, 'APPROVED'::text, 'PUBLISHED'::text, 'BLOCKED'::text, 'DUPLICATE'::text, 'ARCHIVED'::text])
  ),
  constraint "16_content_topic_priority_check" check (priority between 1 and 3),
  constraint "16_content_topic_scope_bike_check" check (
    (normalized_scope = 'GENERIC' and bike_model_id is null)
    or (normalized_scope = 'MODEL' and bike_model_id is not null)
  ),
  constraint "16_content_topic_published_content_check" check (
    status <> 'PUBLISHED' or content_id is not null
  ),
  constraint "16_content_topic_bike_model_id_fkey"
    foreign key (bike_model_id) references public."02_bike_model" (bike_model_id)
    on update no action on delete no action,
  constraint "16_content_topic_content_id_fkey"
    foreign key (content_id) references public."12_content" (content_id)
    on update no action on delete no action,
  constraint "uq_16_content_topic_content_id" unique (content_id)
);

create index "idx_16_content_topic_queue"
  on public."16_content_topic" (status, priority, created_at, content_topic_id);

create index "idx_16_content_topic_intent"
  on public."16_content_topic" (normalized_scope, normalized_subject, normalized_action, content_type, part_type, bike_model_id);

create index "idx_16_content_topic_bike_model_id"
  on public."16_content_topic" (bike_model_id)
  where bike_model_id is not null;

create trigger "trg_16_content_topic_updated_at"
before update on public."16_content_topic"
for each row execute function public.set_updated_at();

alter table public."16_content_topic" enable row level security;

commit;
