-- Expand model/year service specifications.
-- Production migration applied through Supabase on 2026-09-21.

alter table public."03_bike_model_year"
  add column if not exists engine_type text,
  add column if not exists cooling_type text,
  add column if not exists fuel_system text,
  add column if not exists transmission_type text,
  add column if not exists max_power_kw numeric(6,2),
  add column if not exists max_power_ps numeric(6,2),
  add column if not exists max_power_rpm integer,
  add column if not exists max_torque_nm numeric(7,2),
  add column if not exists max_torque_rpm integer,
  add column if not exists length_mm integer,
  add column if not exists width_mm integer,
  add column if not exists height_mm integer,
  add column if not exists wheelbase_mm integer,
  add column if not exists seat_height_mm integer,
  add column if not exists curb_weight_kg numeric(6,1),
  add column if not exists fuel_capacity_l numeric(5,1),
  add column if not exists price_min_krw integer,
  add column if not exists price_max_krw integer,
  add column if not exists price_verified_at date,
  add column if not exists engine_oil_change_l numeric(5,2),
  add column if not exists engine_oil_filter_change_l numeric(5,2),
  add column if not exists engine_oil_total_l numeric(5,2),
  add column if not exists engine_oil_sae text,
  add column if not exists engine_oil_api text,
  add column if not exists engine_oil_jaso text;

create table if not exists public."12_bike_model_alias" (
  alias_id bigint generated by default as identity primary key,
  bike_model_id bigint not null references public."02_bike_model"(bike_model_id) on delete cascade,
  alias text not null,
  alias_type text not null default 'SEARCH',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (bike_model_id, alias)
);

create index if not exists idx_bike_model_alias_lookup on public."12_bike_model_alias" (lower(alias)) where is_active = true;

create table if not exists public."13_bike_reference" (
  reference_id bigint generated by default as identity primary key,
  bike_model_id bigint references public."02_bike_model"(bike_model_id) on delete cascade,
  bike_model_year_id bigint references public."03_bike_model_year"(bike_model_year_id) on delete cascade,
  reference_type text not null,
  title text not null,
  publisher text,
  market_code text,
  language_code text,
  source_url text not null,
  document_code text,
  published_at date,
  verified_at timestamptz,
  verification_status text not null default 'UNVERIFIED',
  note text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bike_reference_target_check check (bike_model_id is not null or bike_model_year_id is not null)
);

create index if not exists idx_bike_reference_model on public."13_bike_reference" (bike_model_id) where is_active = true;
create index if not exists idx_bike_reference_model_year on public."13_bike_reference" (bike_model_year_id) where is_active = true;
