-- Server-side source asset ingest for Scheduled Image Producers.
create extension if not exists pg_net with schema extensions;

create table if not exists public."24_content_pipeline_asset_ingest" (
  ingest_id bigint generated by default as identity primary key,
  pipeline_image_id bigint not null references public."21_content_pipeline_image"(pipeline_image_id) on delete cascade,
  pipeline_id bigint not null references public."18_content_pipeline"(pipeline_id) on delete cascade,
  claim_token uuid not null, token_hash bytea not null unique,
  status text not null default 'QUEUED' check (status in ('QUEUED','PROCESSING','UPLOADED','REUSED','FAILED')),
  source_type text not null check (source_type in ('DIRECT_PHOTO','BRAND_APPROVED','OFFICIAL','BLOG','WIKIMEDIA','LICENSED_WEB','OTHER')),
  source_page_url text, source_asset_url text not null, source_owner text, license_name text, license_url text,
  rights_status text not null check (rights_status in ('OWNED_APPROVED','LICENSED_APPROVED','PERMISSION_CONFIRMED')),
  expires_at timestamptz not null default (now()+interval '15 minutes'), consumed_at timestamptz,
  storage_bucket text, storage_path text, sha256 text, error text, http_request_id bigint,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public."24_content_pipeline_asset_ingest" enable row level security;
revoke all on public."24_content_pipeline_asset_ingest" from public,anon,authenticated;
grant all on public."24_content_pipeline_asset_ingest" to service_role;

create or replace function public.content_pipeline_consume_source_ingest_v1(p_ingest_id bigint,p_token text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare j public."24_content_pipeline_asset_ingest"%rowtype;
begin
 select * into j from public."24_content_pipeline_asset_ingest" where ingest_id=p_ingest_id for update;
 if not found or j.status<>'QUEUED' or j.expires_at<=now() or j.token_hash is distinct from extensions.digest(convert_to(p_token,'UTF8'),'sha256') then return null; end if;
 update public."24_content_pipeline_asset_ingest" set status='PROCESSING',consumed_at=now(),updated_at=now() where ingest_id=j.ingest_id;
 return jsonb_build_object('ingestId',j.ingest_id,'pipelineImageId',j.pipeline_image_id,'pipelineId',j.pipeline_id,
 'contentKey',(select content_key from public."18_content_pipeline" where pipeline_id=j.pipeline_id),
 'assetKey',(select asset_key from public."21_content_pipeline_image" where pipeline_image_id=j.pipeline_image_id),'sourceAssetUrl',j.source_asset_url);
end $$;

create or replace function public.content_pipeline_finish_source_ingest_v1(p_ingest_id bigint,p_status text,p_storage_bucket text,p_storage_path text,p_sha256 text,p_error text)
returns boolean language plpgsql security definer set search_path='' as $$
declare j public."24_content_pipeline_asset_ingest"%rowtype; i public."21_content_pipeline_image"%rowtype; p public."18_content_pipeline"%rowtype; v_role text;
begin
 if p_status not in ('UPLOADED','REUSED','FAILED') then raise exception using errcode='22023',message='INVALID_INGEST_STATUS'; end if;
 select * into j from public."24_content_pipeline_asset_ingest" where ingest_id=p_ingest_id for update;
 if not found or j.status not in ('PROCESSING','QUEUED') then return false; end if;
 select * into i from public."21_content_pipeline_image" where pipeline_image_id=j.pipeline_image_id for update;
 select * into p from public."18_content_pipeline" where pipeline_id=j.pipeline_id;
 update public."24_content_pipeline_asset_ingest" set status=p_status,storage_bucket=p_storage_bucket,storage_path=p_storage_path,sha256=p_sha256,error=left(p_error,1500),updated_at=now() where ingest_id=j.ingest_id;
 if p_status in ('UPLOADED','REUSED') then
   update public."21_content_pipeline_image" set file_status='PASS',upload_status=p_status,storage_bucket=p_storage_bucket,storage_path=p_storage_path,sha256=p_sha256,retry_action='VERIFY_INGESTED_SOURCE',next_eligible_at=now(),updated_at=now() where pipeline_image_id=j.pipeline_image_id;
   v_role:=case when i.asset_key='thumbnail' then 'THUMBNAIL' when i.asset_key='hero' then 'HERO' else 'BODY' end;
   insert into public."17_content_asset_source"(content_id,content_key,asset_role,asset_key,storage_path,source_type,source_page_url,source_asset_url,source_owner,license_name,license_url,rights_status,edited,edit_description,used_in_service,last_checked_at)
   values(null,p.content_key,v_role,i.asset_key,p_storage_path,j.source_type,j.source_page_url,j.source_asset_url,j.source_owner,j.license_name,j.license_url,j.rights_status,true,'Scheduled source ingest → WebP normalization',false,now())
   on conflict (content_key,asset_key) do update set storage_path=excluded.storage_path,source_type=excluded.source_type,source_page_url=excluded.source_page_url,source_asset_url=excluded.source_asset_url,source_owner=excluded.source_owner,license_name=excluded.license_name,license_url=excluded.license_url,rights_status=excluded.rights_status,edited=true,edit_description=excluded.edit_description,last_checked_at=now(),updated_at=now();
 end if; return true;
end $$;

create or replace function public.content_pipeline_request_source_ingest_v1(p_pipeline_image_id bigint,p_claim_token uuid,p_source_type text,p_source_page_url text,p_source_asset_url text,p_source_owner text,p_license_name text,p_license_url text,p_rights_status text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare i public."21_content_pipeline_image"%rowtype; v_token text; v_hash bytea; v_id bigint; v_req bigint;
begin
 if p_source_type not in ('DIRECT_PHOTO','BRAND_APPROVED','OFFICIAL','BLOG','WIKIMEDIA','LICENSED_WEB','OTHER') or p_rights_status not in ('OWNED_APPROVED','LICENSED_APPROVED','PERMISSION_CONFIRMED') or p_source_asset_url !~ '^https://[^[:space:]]+$' then raise exception using errcode='22023',message='SOURCE_INGEST_VALIDATION_FAILED'; end if;
 select * into i from public."21_content_pipeline_image" where pipeline_image_id=p_pipeline_image_id for update;
 if not found or i.status<>'PROCESSING' or i.claim_token is distinct from p_claim_token then raise exception using errcode='40001',message='CONTENT_PIPELINE_IMAGE_CLAIM_CONFLICT'; end if;
 if coalesce((i.generation_contract->>'generation_allowed')::boolean,true)<>false then raise exception using errcode='22023',message='SOURCE_INGEST_ONLY_FOR_REAL_ASSET_CONTRACT'; end if;
 v_token:=encode(extensions.gen_random_bytes(32),'hex'); v_hash:=extensions.digest(convert_to(v_token,'UTF8'),'sha256');
 insert into public."24_content_pipeline_asset_ingest"(pipeline_image_id,pipeline_id,claim_token,token_hash,source_type,source_page_url,source_asset_url,source_owner,license_name,license_url,rights_status)
 values(i.pipeline_image_id,i.pipeline_id,p_claim_token,v_hash,p_source_type,p_source_page_url,p_source_asset_url,p_source_owner,p_license_name,p_license_url,p_rights_status) returning ingest_id into v_id;
 select net.http_post(url:='https://farjyjcvduthawpdjuqe.supabase.co/functions/v1/content-pipeline-source-ingest',headers:='{"Content-Type":"application/json"}'::jsonb,body:=jsonb_build_object('ingestId',v_id,'token',v_token),timeout_milliseconds:=15000) into v_req;
 update public."24_content_pipeline_asset_ingest" set http_request_id=v_req,updated_at=now() where ingest_id=v_id;
 return jsonb_build_object('ingestId',v_id,'status','QUEUED');
end $$;

revoke all on function public.content_pipeline_consume_source_ingest_v1(bigint,text) from public,anon,authenticated;
revoke all on function public.content_pipeline_finish_source_ingest_v1(bigint,text,text,text,text,text) from public,anon,authenticated;
revoke all on function public.content_pipeline_request_source_ingest_v1(bigint,uuid,text,text,text,text,text,text,text) from public,anon,authenticated;
grant execute on function public.content_pipeline_consume_source_ingest_v1(bigint,text) to service_role;
grant execute on function public.content_pipeline_finish_source_ingest_v1(bigint,text,text,text,text,text) to service_role;
grant execute on function public.content_pipeline_request_source_ingest_v1(bigint,uuid,text,text,text,text,text,text,text) to service_role;
