-- Source Ingest one-time tickets for scheduled real-asset ingestion.
create table if not exists public."24_content_pipeline_source_ingest_ticket" (
  ticket_id bigint generated by default as identity primary key,
  pipeline_id bigint not null references public."18_content_pipeline"(pipeline_id) on delete cascade,
  pipeline_image_id bigint not null references public."21_content_pipeline_image"(pipeline_image_id) on delete cascade,
  asset_key text not null check (asset_key ~ '^(thumbnail|hero|body-[0-9]{2})$'),
  token_hash bytea not null unique,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now(),
  claim_token uuid not null
);
alter table public."24_content_pipeline_source_ingest_ticket" enable row level security;
revoke all on public."24_content_pipeline_source_ingest_ticket" from anon, authenticated;

create or replace function public.content_pipeline_issue_source_ingest_ticket_v1(p_pipeline_image_id bigint,p_claim_token uuid)
returns jsonb language plpgsql security definer set search_path to 'public','extensions'
as $$
declare v_pipeline public."18_content_pipeline"%rowtype; v_image public."21_content_pipeline_image"%rowtype;
v_token text; v_expires_at timestamptz:=now()+interval '15 minutes';
begin
 select * into v_image from public."21_content_pipeline_image" where pipeline_image_id=p_pipeline_image_id for update;
 if not found then raise exception 'PIPELINE_IMAGE_NOT_FOUND'; end if;
 if v_image.status<>'PROCESSING' or v_image.claim_token is null or v_image.claim_token<>p_claim_token or v_image.claim_expires_at<=now()
 then raise exception 'IMAGE_NOT_ACTIVELY_CLAIMED'; end if;
 select * into v_pipeline from public."18_content_pipeline" where pipeline_id=v_image.pipeline_id for update;
 if not found or v_pipeline.ownership_state<>'CLAIMED' then raise exception 'PIPELINE_NOT_CLAIMED'; end if;
 if v_pipeline.content_key is null then raise exception 'CONTENT_KEY_MISSING'; end if;
 delete from public."24_content_pipeline_source_ingest_ticket" where expires_at<now() or consumed_at is not null;
 v_token:=encode(extensions.gen_random_bytes(32),'hex');
 insert into public."24_content_pipeline_source_ingest_ticket"(pipeline_id,pipeline_image_id,asset_key,token_hash,expires_at,claim_token)
 values(v_image.pipeline_id,v_image.pipeline_image_id,v_image.asset_key,extensions.digest(v_token,'sha256'),v_expires_at,v_image.claim_token);
 return jsonb_build_object('pipelineId',v_image.pipeline_id,'pipelineImageId',v_image.pipeline_image_id,'contentKey',v_pipeline.content_key,'assetKey',v_image.asset_key,'ticket',v_token,'expiresAt',v_expires_at);
end $$;

create or replace function public.content_pipeline_consume_source_ingest_ticket_v1(
 p_pipeline_id bigint,p_pipeline_image_id bigint,p_content_key text,p_asset_key text,p_ticket text)
returns boolean language plpgsql security definer set search_path to 'public','extensions'
as $$
declare v_ticket_id bigint;
begin
 if p_ticket is null or length(p_ticket)<32 then return false; end if;
 select t.ticket_id into v_ticket_id
 from public."24_content_pipeline_source_ingest_ticket" t
 join public."18_content_pipeline" p on p.pipeline_id=t.pipeline_id
 join public."21_content_pipeline_image" i on i.pipeline_image_id=t.pipeline_image_id
 where t.pipeline_id=p_pipeline_id and t.pipeline_image_id=p_pipeline_image_id and p.content_key=p_content_key
   and p.ownership_state='CLAIMED' and t.asset_key=p_asset_key and t.consumed_at is null and t.expires_at>now()
   and t.token_hash=extensions.digest(p_ticket,'sha256') and t.claim_token=i.claim_token
   and i.status='PROCESSING' and i.claim_expires_at>now()
 for update of t;
 if not found then return false; end if;
 update public."24_content_pipeline_source_ingest_ticket" set consumed_at=now() where ticket_id=v_ticket_id;
 return true;
end $$;

revoke all on function public.content_pipeline_issue_source_ingest_ticket_v1(bigint,uuid) from public,anon,authenticated;
revoke all on function public.content_pipeline_consume_source_ingest_ticket_v1(bigint,bigint,text,text,text) from public,anon,authenticated;
grant execute on function public.content_pipeline_issue_source_ingest_ticket_v1(bigint,uuid) to service_role;
grant execute on function public.content_pipeline_consume_source_ingest_ticket_v1(bigint,bigint,text,text,text) to service_role;

create or replace function public.content_pipeline_image_done_storage_guard_v1()
returns trigger language plpgsql security definer set search_path to ''
as $$
declare v_content_key text; v_expected_path text;
begin
 if new.status <> 'DONE' or old.status = 'DONE' then return new; end if;
 select content_key into v_content_key from public."18_content_pipeline" where pipeline_id=new.pipeline_id;
 v_expected_path := 'contents/' || v_content_key || '/' || new.asset_key || '.webp';
 if new.storage_bucket is distinct from 'content-assets' or new.storage_path is distinct from v_expected_path
    or new.sha256 !~ '^[0-9a-f]{64}$' then
   raise exception using errcode='22023',message='CONTENT_PIPELINE_IMAGE_INVALID_STORAGE_PROOF';
 end if;
 if not exists(select 1 from storage.objects o where o.bucket_id='content-assets' and o.name=v_expected_path
   and o.metadata->>'mimetype'='image/webp' and (o.metadata->>'size')::bigint between 1 and 4194304) then
   raise exception using errcode='22023',message='CONTENT_PIPELINE_IMAGE_STORAGE_OBJECT_MISSING';
 end if;
 if not (
   exists(select 1 from public."20_content_pipeline_asset_upload_ticket" t where t.pipeline_id=new.pipeline_id
     and t.asset_key=new.asset_key and t.claim_token=old.claim_token and t.consumed_at is not null)
   or exists(select 1 from public."24_content_pipeline_source_ingest_ticket" t where t.pipeline_id=new.pipeline_id
     and t.pipeline_image_id=new.pipeline_image_id and t.asset_key=new.asset_key
     and t.claim_token=old.claim_token and t.consumed_at is not null)
 ) then raise exception using errcode='22023',message='CONTENT_PIPELINE_IMAGE_UPLOAD_TICKET_MISSING'; end if;
 return new;
end $$;
