-- Applied to production as migration 20260928045934.
-- Scheduled Content Factory state store. Internal/service-role only.

begin;

create table public."18_content_pipeline" (
  pipeline_id bigint generated by default as identity primary key,
  content_topic_id bigint not null unique references public."16_content_topic"(content_topic_id) on delete restrict,
  topic_key text not null unique,
  content_key text,
  stage text not null default 'PLANNING' check (stage = any (array[
    'PLANNING','PLANNED','RESEARCHING','RESEARCHED','WRITING','DRAFTED',
    'VISUAL','IMAGE_READY','QA','QA_PASS','PUBLISHING','COMPLETE','HOLD','BLOCKED'
  ])),
  planning_artifact jsonb not null default '{}'::jsonb,
  research_artifact jsonb not null default '{}'::jsonb,
  writer_artifact jsonb not null default '{}'::jsonb,
  image_manifest jsonb not null default '[]'::jsonb check (jsonb_typeof(image_manifest) = 'array'),
  qa_artifact jsonb not null default '{}'::jsonb,
  publish_artifact jsonb not null default '{}'::jsonb,
  content_id bigint references public."12_content"(content_id) on delete set null,
  production_url text,
  last_error text,
  retry_count integer not null default 0 check (retry_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);
create index "18_content_pipeline_stage_idx" on public."18_content_pipeline"(stage, updated_at, pipeline_id);

create table public."19_content_pipeline_run" (
  pipeline_run_id bigint generated by default as identity primary key,
  pipeline_id bigint not null references public."18_content_pipeline"(pipeline_id) on delete cascade,
  stage text not null,
  status text not null default 'RUNNING' check (status = any (array['RUNNING','PASS','SKIP','HOLD','BLOCKED','FAILED'])),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  summary text,
  error text,
  metadata jsonb not null default '{}'::jsonb
);
create index "19_content_pipeline_run_pipeline_idx" on public."19_content_pipeline_run"(pipeline_id, started_at desc);

alter table public."18_content_pipeline" enable row level security;
alter table public."19_content_pipeline_run" enable row level security;
revoke all on table public."18_content_pipeline" from public, anon, authenticated;
revoke all on table public."19_content_pipeline_run" from public, anon, authenticated;
grant select, insert, update, delete on table public."18_content_pipeline" to service_role;
grant select, insert, update, delete on table public."19_content_pipeline_run" to service_role;
grant usage, select on sequence public."18_content_pipeline_pipeline_id_seq" to service_role;
grant usage, select on sequence public."19_content_pipeline_run_pipeline_run_id_seq" to service_role;

create or replace function public.content_pipeline_claim_planning_v1()
returns jsonb language plpgsql security definer set search_path='' as $$
declare t public."16_content_topic"%rowtype; p public."18_content_pipeline"%rowtype; r_id bigint;
begin
  select * into t from public."16_content_topic"
  where status='PLANNED' and content_id is null
    and not exists (select 1 from public."18_content_pipeline" p0 where p0.content_topic_id="16_content_topic".content_topic_id)
  order by priority,created_at,content_topic_id for update skip locked limit 1;
  if not found then return null; end if;
  insert into public."18_content_pipeline"(content_topic_id,topic_key,stage)
    values(t.content_topic_id,t.topic_key,'PLANNING') returning * into p;
  update public."16_content_topic" set status='GENERATING',last_error=null
    where content_topic_id=t.content_topic_id and status='PLANNED';
  insert into public."19_content_pipeline_run"(pipeline_id,stage,status)
    values(p.pipeline_id,'PLANNING','RUNNING') returning pipeline_run_id into r_id;
  return jsonb_build_object('pipelineId',p.pipeline_id,'pipelineRunId',r_id,'topic',to_jsonb(t),'stage',p.stage);
end $$;

create or replace function public.content_pipeline_claim_stage_v1(p_expected_stage text,p_running_stage text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare p public."18_content_pipeline"%rowtype; r_id bigint;
begin
  if not ((p_expected_stage='PLANNED' and p_running_stage='RESEARCHING')
    or (p_expected_stage='RESEARCHED' and p_running_stage='WRITING')
    or (p_expected_stage='DRAFTED' and p_running_stage='VISUAL')
    or (p_expected_stage='IMAGE_READY' and p_running_stage='QA')
    or (p_expected_stage='QA_PASS' and p_running_stage='PUBLISHING'))
  then raise exception using errcode='22023',message='CONTENT_PIPELINE_INVALID_CLAIM'; end if;
  select * into p from public."18_content_pipeline" where stage=p_expected_stage
    order by updated_at,pipeline_id for update skip locked limit 1;
  if not found then return null; end if;
  update public."18_content_pipeline" set stage=p_running_stage,updated_at=now(),last_error=null
    where pipeline_id=p.pipeline_id returning * into p;
  insert into public."19_content_pipeline_run"(pipeline_id,stage,status)
    values(p.pipeline_id,p_running_stage,'RUNNING') returning pipeline_run_id into r_id;
  return jsonb_build_object('pipelineId',p.pipeline_id,'pipelineRunId',r_id,'pipeline',to_jsonb(p));
end $$;

create or replace function public.content_pipeline_complete_stage_v1(
  p_pipeline_id bigint,p_pipeline_run_id bigint,p_expected_stage text,p_next_stage text,
  p_artifact jsonb default '{}'::jsonb,p_image_manifest jsonb default null,p_content_key text default null,
  p_content_id bigint default null,p_production_url text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare p public."18_content_pipeline"%rowtype;
begin
  if not ((p_expected_stage='PLANNING' and p_next_stage='PLANNED')
    or (p_expected_stage='RESEARCHING' and p_next_stage='RESEARCHED')
    or (p_expected_stage='WRITING' and p_next_stage='DRAFTED')
    or (p_expected_stage='VISUAL' and p_next_stage='IMAGE_READY')
    or (p_expected_stage='QA' and p_next_stage='QA_PASS')
    or (p_expected_stage='PUBLISHING' and p_next_stage='COMPLETE'))
  then raise exception using errcode='22023',message='CONTENT_PIPELINE_INVALID_COMPLETION'; end if;
  select * into p from public."18_content_pipeline" where pipeline_id=p_pipeline_id for update;
  if not found or p.stage<>p_expected_stage then raise exception using errcode='40001',message='CONTENT_PIPELINE_STATE_CONFLICT'; end if;
  update public."18_content_pipeline" set stage=p_next_stage,
    planning_artifact=case when p_next_stage='PLANNED' then coalesce(p_artifact,'{}'::jsonb) else planning_artifact end,
    research_artifact=case when p_next_stage='RESEARCHED' then coalesce(p_artifact,'{}'::jsonb) else research_artifact end,
    writer_artifact=case when p_next_stage='DRAFTED' then coalesce(p_artifact,'{}'::jsonb) else writer_artifact end,
    image_manifest=case when p_next_stage='IMAGE_READY' then coalesce(p_image_manifest,'[]'::jsonb) else image_manifest end,
    qa_artifact=case when p_next_stage='QA_PASS' then coalesce(p_artifact,'{}'::jsonb) else qa_artifact end,
    publish_artifact=case when p_next_stage='COMPLETE' then coalesce(p_artifact,'{}'::jsonb) else publish_artifact end,
    content_key=coalesce(p_content_key,content_key),content_id=coalesce(p_content_id,content_id),
    production_url=coalesce(p_production_url,production_url),last_error=null,updated_at=now(),
    completed_at=case when p_next_stage='COMPLETE' then now() else completed_at end
    where pipeline_id=p_pipeline_id returning * into p;
  if p_next_stage='QA_PASS' then
    update public."16_content_topic" set status='APPROVED',last_error=null
      where content_topic_id=p.content_topic_id and status='GENERATING';
    if not found then raise exception using errcode='40001',message='CONTENT_PIPELINE_TOPIC_APPROVAL_CONFLICT'; end if;
  end if;
  if p_next_stage='COMPLETE' then
    if p.content_id is null or p.production_url is null then raise exception using errcode='22023',message='CONTENT_PIPELINE_PRODUCTION_QA_REQUIRED'; end if;
    if not exists(select 1 from public."16_content_topic" t where t.content_topic_id=p.content_topic_id and t.status='PUBLISHED' and t.content_id=p.content_id)
      then raise exception using errcode='40001',message='CONTENT_PIPELINE_TOPIC_NOT_PUBLISHED'; end if;
  end if;
  update public."19_content_pipeline_run" set status='PASS',completed_at=now(),summary=p_next_stage
    where pipeline_run_id=p_pipeline_run_id and pipeline_id=p_pipeline_id and status='RUNNING';
  return jsonb_build_object('pipelineId',p.pipeline_id,'topicKey',p.topic_key,'stage',p.stage,'contentKey',p.content_key,'productionUrl',p.production_url);
end $$;

create or replace function public.content_pipeline_fail_stage_v1(
  p_pipeline_id bigint,p_pipeline_run_id bigint,p_expected_stage text,p_failure_status text,p_error text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare p public."18_content_pipeline"%rowtype;
begin
  if p_failure_status not in ('HOLD','BLOCKED') then raise exception using errcode='22023',message='CONTENT_PIPELINE_INVALID_FAILURE_STATUS'; end if;
  update public."18_content_pipeline" set stage=p_failure_status,last_error=left(p_error,2000),
    retry_count=retry_count+1,updated_at=now()
    where pipeline_id=p_pipeline_id and stage=p_expected_stage returning * into p;
  if not found then raise exception using errcode='40001',message='CONTENT_PIPELINE_STATE_CONFLICT'; end if;
  update public."16_content_topic" set status='BLOCKED',last_error=left(p_error,1000)
    where content_topic_id=p.content_topic_id and status in ('GENERATING','APPROVED');
  update public."19_content_pipeline_run" set status=p_failure_status,completed_at=now(),error=left(p_error,2000)
    where pipeline_run_id=p_pipeline_run_id and pipeline_id=p_pipeline_id and status='RUNNING';
  return jsonb_build_object('pipelineId',p.pipeline_id,'topicKey',p.topic_key,'stage',p.stage,'error',p.last_error);
end $$;

revoke all on function public.content_pipeline_claim_planning_v1() from public,anon,authenticated;
revoke all on function public.content_pipeline_claim_stage_v1(text,text) from public,anon,authenticated;
revoke all on function public.content_pipeline_complete_stage_v1(bigint,bigint,text,text,jsonb,jsonb,text,bigint,text) from public,anon,authenticated;
revoke all on function public.content_pipeline_fail_stage_v1(bigint,bigint,text,text,text) from public,anon,authenticated;
grant execute on function public.content_pipeline_claim_planning_v1() to service_role;
grant execute on function public.content_pipeline_claim_stage_v1(text,text) to service_role;
grant execute on function public.content_pipeline_complete_stage_v1(bigint,bigint,text,text,jsonb,jsonb,text,bigint,text) to service_role;
grant execute on function public.content_pipeline_fail_stage_v1(bigint,bigint,text,text,text) to service_role;

comment on table public."18_content_pipeline" is 'Scheduled Content Factory pipeline state and stage artifacts; internal service-role only.';
comment on table public."19_content_pipeline_run" is 'Scheduled Content Factory execution history; internal service-role only.';

commit;
