begin;

create table public."12_content" (
  content_id bigint generated by default as identity primary key,
  content_key text not null unique,
  title text not null,
  summary text not null,
  content_type text not null,
  thumbnail_image_storage_path text,
  hero_image_storage_path text,
  body_blocks jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  published_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint "12_content_content_type_check" check (
    content_type = any (
      array[
        'MAINTENANCE'::text,
        'DIY'::text,
        'PARTS_GUIDE'::text,
        'MODEL_GUIDE'::text
      ]
    )
  ),
  constraint "12_content_body_blocks_array_check" check (
    jsonb_typeof(body_blocks) = 'array'
  )
);

create table public."13_content_bike_model" (
  content_bike_model_id bigint generated by default as identity primary key,
  content_id bigint not null,
  bike_model_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint "13_content_bike_model_content_id_fkey"
    foreign key (content_id)
    references public."12_content" (content_id)
    on update no action
    on delete cascade,
  constraint "13_content_bike_model_bike_model_id_fkey"
    foreign key (bike_model_id)
    references public."02_bike_model" (bike_model_id)
    on update no action
    on delete no action,
  constraint "uq_13_content_bike_model"
    unique (content_id, bike_model_id)
);

create table public."14_content_bike_model_year" (
  content_bike_model_year_id bigint generated by default as identity primary key,
  content_id bigint not null,
  bike_model_year_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint "14_content_bike_model_year_content_id_fkey"
    foreign key (content_id)
    references public."12_content" (content_id)
    on update no action
    on delete cascade,
  constraint "14_content_bike_model_year_bike_model_year_id_fkey"
    foreign key (bike_model_year_id)
    references public."03_bike_model_year" (bike_model_year_id)
    on update no action
    on delete no action,
  constraint "uq_14_content_bike_model_year"
    unique (content_id, bike_model_year_id)
);

create table public."15_content_part_link" (
  content_part_link_id bigint generated by default as identity primary key,
  content_id bigint not null,
  part_type text not null,
  scope_type text not null,
  tire_model_id bigint,
  tire_product_id bigint,
  battery_product_id bigint,
  brake_product_id bigint,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint "15_content_part_link_content_id_fkey"
    foreign key (content_id)
    references public."12_content" (content_id)
    on update no action
    on delete cascade,
  constraint "15_content_part_link_tire_model_id_fkey"
    foreign key (tire_model_id)
    references public."11_tire_model" (tire_model_id)
    on update no action
    on delete no action,
  constraint "15_content_part_link_tire_product_id_fkey"
    foreign key (tire_product_id)
    references public."04_tire_product" (tire_product_id)
    on update no action
    on delete no action,
  constraint "15_content_part_link_battery_product_id_fkey"
    foreign key (battery_product_id)
    references public."05_battery_product" (battery_product_id)
    on update no action
    on delete no action,
  constraint "15_content_part_link_brake_product_id_fkey"
    foreign key (brake_product_id)
    references public."06_brake_product" (brake_product_id)
    on update no action
    on delete no action,
  constraint "15_content_part_link_part_type_check" check (
    part_type = any (
      array['TIRE'::text, 'BATTERY'::text, 'BRAKE'::text]
    )
  ),
  constraint "15_content_part_link_scope_type_check" check (
    scope_type = any (
      array['CATEGORY'::text, 'MODEL'::text, 'PRODUCT'::text]
    )
  ),
  constraint "15_content_part_link_target_check" check (
    (
      scope_type = 'CATEGORY'
      and tire_model_id is null
      and tire_product_id is null
      and battery_product_id is null
      and brake_product_id is null
    )
    or (
      scope_type = 'MODEL'
      and part_type = 'TIRE'
      and tire_model_id is not null
      and tire_product_id is null
      and battery_product_id is null
      and brake_product_id is null
    )
    or (
      scope_type = 'PRODUCT'
      and part_type = 'TIRE'
      and tire_model_id is null
      and tire_product_id is not null
      and battery_product_id is null
      and brake_product_id is null
    )
    or (
      scope_type = 'PRODUCT'
      and part_type = 'BATTERY'
      and tire_model_id is null
      and tire_product_id is null
      and battery_product_id is not null
      and brake_product_id is null
    )
    or (
      scope_type = 'PRODUCT'
      and part_type = 'BRAKE'
      and tire_model_id is null
      and tire_product_id is null
      and battery_product_id is null
      and brake_product_id is not null
    )
  )
);

create index "idx_12_content_content_type"
  on public."12_content" (content_type);

create index "idx_12_content_publication"
  on public."12_content" (is_active, published_at desc);

create index "idx_13_content_bike_model_bike_model_id"
  on public."13_content_bike_model" (bike_model_id);

create index "idx_14_content_bike_model_year_bike_model_year_id"
  on public."14_content_bike_model_year" (bike_model_year_id);

create index "idx_15_content_part_link_content_id"
  on public."15_content_part_link" (content_id);

create index "idx_15_content_part_link_part_type"
  on public."15_content_part_link" (part_type);

create index "idx_15_content_part_link_is_active"
  on public."15_content_part_link" (is_active);

create trigger "trg_12_content_updated_at"
before update on public."12_content"
for each row execute function public.set_updated_at();

create trigger "trg_15_content_part_link_updated_at"
before update on public."15_content_part_link"
for each row execute function public.set_updated_at();

alter table public."12_content" enable row level security;
alter table public."13_content_bike_model" enable row level security;
alter table public."14_content_bike_model_year" enable row level security;
alter table public."15_content_part_link" enable row level security;

grant select on table public."12_content" to anon, authenticated;
grant select on table public."13_content_bike_model" to anon, authenticated;
grant select on table public."14_content_bike_model_year" to anon, authenticated;
grant select on table public."15_content_part_link" to anon, authenticated;

create policy "Public can read published content"
on public."12_content"
for select
to anon, authenticated
using (
  is_active = true
  and published_at is not null
  and published_at <= now()
);

create policy "Public can read published content bike models"
on public."13_content_bike_model"
for select
to anon, authenticated
using (
  exists (
    select 1
    from public."12_content" as content
    where content.content_id = "13_content_bike_model".content_id
      and content.is_active = true
      and content.published_at is not null
      and content.published_at <= now()
  )
);

create policy "Public can read published content bike model years"
on public."14_content_bike_model_year"
for select
to anon, authenticated
using (
  exists (
    select 1
    from public."12_content" as content
    where content.content_id = "14_content_bike_model_year".content_id
      and content.is_active = true
      and content.published_at is not null
      and content.published_at <= now()
  )
);

create policy "Public can read published content part links"
on public."15_content_part_link"
for select
to anon, authenticated
using (
  is_active = true
  and exists (
    select 1
    from public."12_content" as content
    where content.content_id = "15_content_part_link".content_id
      and content.is_active = true
      and content.published_at is not null
      and content.published_at <= now()
  )
);

insert into public."12_content" (
  content_key,
  title,
  summary,
  content_type,
  body_blocks,
  is_active,
  published_at
) values (
  'tire-size-guide',
  '타이어 규격 읽는 법',
  '오토바이 타이어에 표시된 폭, 편평비, 휠 크기와 하중·속도 지수의 의미를 확인합니다.',
  'PARTS_GUIDE',
  '[
    {
      "type": "heading",
      "level": 2,
      "text": "타이어 규격은 어떻게 읽나요?"
    },
    {
      "type": "paragraph",
      "text": "타이어 옆면의 120/70ZR17 M/C 58W TL 같은 표기는 크기와 사용 조건을 순서대로 나타냅니다."
    },
    {
      "type": "table",
      "headers": ["표기", "의미"],
      "rows": [
        ["120", "타이어 폭(mm)"],
        ["70", "편평비(%)"],
        ["ZR", "구조·속도 관련 표기"],
        ["17", "휠 지름(인치)"],
        ["58", "하중지수"],
        ["W", "속도등급"],
        ["TL", "튜브리스(Tubeless)"]
      ]
    },
    {
      "type": "tip",
      "title": "장착 전 확인",
      "body": "실제 장착 규격은 바이크 모델과 연식별 제원을 기준으로 확인해야 합니다."
    }
  ]'::jsonb,
  true,
  now()
);

commit;
