create table if not exists public."20_content_pipeline_asset_upload_ticket" (
  ticket_id bigint generated by default as identity primary key,
  pipeline_id bigint not null references public."18_content_pipeline"(pipeline_id) on delete cascade,
  asset_key text not null check (asset_key ~ '^(thumbnail|hero|body-[0-9]{2})$'),
  token_hash bytea not null unique,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public."20_content_pipeline_asset_upload_ticket" enable row level security;
revoke all on table public."20_content_pipeline_asset_upload_ticket" from public, anon, authenticated;
grant all on table public."20_content_pipeline_asset_upload_ticket" to service_role;

create or replace function public.content_pipeline_issue_asset_upload_ticket_v1(
  p_pipeline_id bigint,
  p_asset_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_pipeline public."18_content_pipeline"%rowtype;
  v_token text;
  v_expires_at timestamptz := now() + interval '15 minutes';
begin
  if p_asset_key !~ '^(thumbnail|hero|body-[0-9]{2})$' then raise exception 'INVALID_ASSET_KEY'; end if;

  select * into v_pipeline
  from public."18_content_pipeline"
  where pipeline_id = p_pipeline_id
  for update;

  if not found then raise exception 'PIPELINE_NOT_FOUND'; end if;
  if v_pipeline.ownership_state <> 'CLAIMED' then raise exception 'PIPELINE_NOT_CLAIMED'; end if;
  if v_pipeline.content_key is null then raise exception 'CONTENT_KEY_MISSING'; end if;

  if not exists (
    select 1
    from jsonb_array_elements(coalesce(v_pipeline.image_manifest, '[]'::jsonb)) item
    where item->>'asset_key' = p_asset_key
  ) then
    raise exception 'ASSET_NOT_IN_MANIFEST';
  end if;

  delete from public."20_content_pipeline_asset_upload_ticket"
  where expires_at < now() or consumed_at is not null;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');

  insert into public."20_content_pipeline_asset_upload_ticket"(pipeline_id, asset_key, token_hash, expires_at)
  values (p_pipeline_id, p_asset_key, extensions.digest(v_token, 'sha256'), v_expires_at);

  return jsonb_build_object(
    'pipelineId', p_pipeline_id,
    'contentKey', v_pipeline.content_key,
    'assetKey', p_asset_key,
    'ticket', v_token,
    'expiresAt', v_expires_at
  );
end;
$$;

create or replace function public.content_pipeline_consume_asset_upload_ticket_v1(
  p_pipeline_id bigint,
  p_content_key text,
  p_asset_key text,
  p_ticket text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_ticket_id bigint;
begin
  if p_ticket is null or length(p_ticket) < 32 then return false; end if;

  select t.ticket_id into v_ticket_id
  from public."20_content_pipeline_asset_upload_ticket" t
  join public."18_content_pipeline" p on p.pipeline_id = t.pipeline_id
  where t.pipeline_id = p_pipeline_id
    and p.content_key = p_content_key
    and p.ownership_state = 'CLAIMED'
    and t.asset_key = p_asset_key
    and t.consumed_at is null
    and t.expires_at > now()
    and t.token_hash = extensions.digest(p_ticket, 'sha256')
  for update of t;

  if not found then return false; end if;

  update public."20_content_pipeline_asset_upload_ticket"
  set consumed_at = now()
  where ticket_id = v_ticket_id;

  return true;
end;
$$;

revoke all on function public.content_pipeline_issue_asset_upload_ticket_v1(bigint,text) from public, anon, authenticated;
revoke all on function public.content_pipeline_consume_asset_upload_ticket_v1(bigint,text,text,text) from public, anon, authenticated;
grant execute on function public.content_pipeline_issue_asset_upload_ticket_v1(bigint,text) to service_role;
grant execute on function public.content_pipeline_consume_asset_upload_ticket_v1(bigint,text,text,text) to service_role;
