-- Image-level queue/claim state for Scheduled Content Factory.
-- Production-applied before this migration was committed.

create table if not exists public."21_content_pipeline_image" (
  pipeline_image_id bigint generated by default as identity primary key,
  pipeline_id bigint not null references public."18_content_pipeline"(pipeline_id) on delete cascade,
  image_id text not null,
  asset_key text not null check (asset_key ~ '^(thumbnail|hero|body-[0-9]{2})$'),
  ordinal integer not null check (ordinal >= 0),
  image_brief jsonb not null default '{}'::jsonb,
  status text not null default 'PENDING' check (status in ('PENDING','PROCESSING','RETRY','HOLD','BLOCKED','DONE')),
  retry_action text,
  claimed_by text, claim_token uuid, claimed_at timestamptz, claim_expires_at timestamptz,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  generation_status text not null default 'PENDING',
  qa_status text not null default 'PENDING',
  file_status text not null default 'PENDING',
  upload_status text not null default 'PENDING',
  storage_bucket text, storage_path text, sha256 text,
  failure_stage text, failure_code text, last_error text,
  completed_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(pipeline_id, asset_key), unique(pipeline_id, image_id)
);
create index if not exists idx_21_content_pipeline_image_queue
  on public."21_content_pipeline_image"(status, claim_expires_at, pipeline_id, ordinal);

create table if not exists public."23_content_pipeline_image_run" (
  pipeline_image_run_id bigint generated by default as identity primary key,
  pipeline_image_id bigint not null references public."21_content_pipeline_image"(pipeline_image_id) on delete cascade,
  pipeline_id bigint not null references public."18_content_pipeline"(pipeline_id) on delete cascade,
  claim_token uuid not null, worker_key text not null, attempt_no integer not null,
  status text not null check (status in ('RUNNING','PASS','RETRY','HOLD','BLOCKED','FAILED')),
  started_at timestamptz not null default now(), completed_at timestamptz,
  failure_stage text, failure_code text, summary text, error text,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists idx_23_content_pipeline_image_run_lookup
  on public."23_content_pipeline_image_run"(pipeline_image_id, pipeline_image_run_id desc);

alter table public."21_content_pipeline_image" enable row level security;
alter table public."23_content_pipeline_image_run" enable row level security;
revoke all on public."21_content_pipeline_image" from public, anon, authenticated;
revoke all on public."23_content_pipeline_image_run" from public, anon, authenticated;
grant select,insert,update,delete on public."21_content_pipeline_image" to service_role;
grant select,insert,update,delete on public."23_content_pipeline_image_run" to service_role;
grant usage,select on all sequences in schema public to service_role;

create or replace function public.content_pipeline_sync_images_v1(p_pipeline_id bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
declare p public."18_content_pipeline"%rowtype; v_count int; v_item jsonb; v_ord int:=0; v_asset text; v_image text;
begin
 select * into p from public."18_content_pipeline" where pipeline_id=p_pipeline_id for update;
 if not found then raise exception using errcode='P0002',message='CONTENT_PIPELINE_NOT_FOUND'; end if;
 if p.ownership_state<>'CLAIMED' then raise exception using errcode='22023',message='CONTENT_PIPELINE_NOT_CLAIMED'; end if;
 if p.stage not in ('DRAFTED','VISUAL','IMAGE_READY') then raise exception using errcode='22023',message='CONTENT_PIPELINE_IMAGES_NOT_AVAILABLE'; end if;
 for v_item in select value from jsonb_array_elements(coalesce(p.writer_artifact->'image_manifest','[]'::jsonb)) loop
   v_asset:=coalesce(v_item->>'asset_key',case when v_ord=0 then 'thumbnail' when v_ord=1 then 'hero' else 'body-'||lpad((v_ord-1)::text,2,'0') end);
   v_image:=coalesce(nullif(v_item->>'image_id',''),'IMAGE_'||lpad((v_ord+1)::text,2,'0'));
   if v_asset !~ '^(thumbnail|hero|body-[0-9]{2})$' then raise exception using errcode='22023',message='CONTENT_PIPELINE_INVALID_IMAGE_ASSET_KEY'; end if;
   insert into public."21_content_pipeline_image"(pipeline_id,image_id,asset_key,ordinal,image_brief)
   values(p_pipeline_id,v_image,v_asset,v_ord,v_item)
   on conflict (pipeline_id,asset_key) do update set
     image_id=excluded.image_id,ordinal=excluded.ordinal,
     image_brief=case when public."21_content_pipeline_image".status in ('PENDING','RETRY') then excluded.image_brief else public."21_content_pipeline_image".image_brief end,
     updated_at=now();
   v_ord:=v_ord+1;
 end loop;
 select count(*) into v_count from public."21_content_pipeline_image" where pipeline_id=p_pipeline_id;
 return jsonb_build_object('pipelineId',p_pipeline_id,'requiredImageCount',v_count);
end $$;

create or replace function public.content_pipeline_claim_image_v1(p_worker_key text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare i public."21_content_pipeline_image"%rowtype; p public."18_content_pipeline"%rowtype; v_token uuid:=extensions.gen_random_uuid(); v_run bigint;
begin
 if p_worker_key is null or length(trim(p_worker_key))<1 or length(p_worker_key)>100 then raise exception using errcode='22023',message='CONTENT_PIPELINE_INVALID_WORKER_KEY'; end if;
 for p in select * from public."18_content_pipeline" where ownership_state='CLAIMED' and stage in ('DRAFTED','VISUAL') order by updated_at,pipeline_id loop
   perform public.content_pipeline_sync_images_v1(p.pipeline_id);
 end loop;
 select i0.* into i from public."21_content_pipeline_image" i0
 join public."18_content_pipeline" p0 on p0.pipeline_id=i0.pipeline_id
 where p0.ownership_state='CLAIMED' and p0.stage in ('DRAFTED','VISUAL')
   and (i0.status in ('PENDING','RETRY') or (i0.status='PROCESSING' and i0.claim_expires_at<now()))
 order by case i0.status when 'RETRY' then 0 when 'PROCESSING' then 1 else 2 end,p0.updated_at,i0.pipeline_id,i0.ordinal
 for update of i0 skip locked limit 1;
 if not found then return null; end if;
 update public."18_content_pipeline" set stage='VISUAL',updated_at=now(),last_error=null where pipeline_id=i.pipeline_id and stage='DRAFTED';
 update public."21_content_pipeline_image" set status='PROCESSING',claimed_by=p_worker_key,claim_token=v_token,claimed_at=now(),
   claim_expires_at=now()+interval '20 minutes',attempt_count=attempt_count+1,failure_stage=null,failure_code=null,last_error=null,updated_at=now()
 where pipeline_image_id=i.pipeline_image_id returning * into i;
 insert into public."23_content_pipeline_image_run"(pipeline_image_id,pipeline_id,claim_token,worker_key,attempt_no,status)
 values(i.pipeline_image_id,i.pipeline_id,v_token,p_worker_key,i.attempt_count,'RUNNING') returning pipeline_image_run_id into v_run;
 select * into p from public."18_content_pipeline" where pipeline_id=i.pipeline_id;
 return jsonb_build_object('pipelineImageId',i.pipeline_image_id,'pipelineImageRunId',v_run,'claimToken',v_token,
   'pipelineId',i.pipeline_id,'contentKey',p.content_key,'topicKey',p.topic_key,'imageId',i.image_id,'assetKey',i.asset_key,
   'ordinal',i.ordinal,'attemptNo',i.attempt_count,'imageBrief',i.image_brief,'writerArtifact',p.writer_artifact,'researchArtifact',p.research_artifact);
end $$;

create or replace function public.content_pipeline_complete_image_v1(
 p_pipeline_image_id bigint,p_pipeline_image_run_id bigint,p_claim_token uuid,
 p_generation_status text,p_qa_status text,p_file_status text,p_upload_status text,
 p_storage_bucket text,p_storage_path text,p_sha256 text,p_metadata jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare i public."21_content_pipeline_image"%rowtype; v_required int; v_done int; v_manifest jsonb;
begin
 select * into i from public."21_content_pipeline_image" where pipeline_image_id=p_pipeline_image_id for update;
 if not found then raise exception using errcode='P0002',message='CONTENT_PIPELINE_IMAGE_NOT_FOUND'; end if;
 if i.status<>'PROCESSING' or i.claim_token is distinct from p_claim_token then raise exception using errcode='40001',message='CONTENT_PIPELINE_IMAGE_CLAIM_CONFLICT'; end if;
 if p_generation_status<>'PASS' or p_qa_status<>'PASS' or p_file_status<>'PASS' or p_upload_status not in ('UPLOADED','REUSED') then raise exception using errcode='22023',message='CONTENT_PIPELINE_IMAGE_NOT_COMPLETE'; end if;
 if p_storage_bucket is null or p_storage_path is null or p_sha256 is null then raise exception using errcode='22023',message='CONTENT_PIPELINE_IMAGE_STORAGE_VERIFY_REQUIRED'; end if;
 update public."21_content_pipeline_image" set status='DONE',generation_status=p_generation_status,qa_status=p_qa_status,file_status=p_file_status,
   upload_status=p_upload_status,storage_bucket=p_storage_bucket,storage_path=p_storage_path,sha256=p_sha256,
   claimed_by=null,claim_token=null,claimed_at=null,claim_expires_at=null,retry_action=null,failure_stage=null,failure_code=null,last_error=null,
   completed_at=now(),updated_at=now() where pipeline_image_id=p_pipeline_image_id returning * into i;
 update public."23_content_pipeline_image_run" set status='PASS',completed_at=now(),summary='DONE',metadata=coalesce(p_metadata,'{}'::jsonb)
 where pipeline_image_run_id=p_pipeline_image_run_id and pipeline_image_id=p_pipeline_image_id and claim_token=p_claim_token and status='RUNNING';
 select count(*),count(*) filter(where status='DONE') into v_required,v_done from public."21_content_pipeline_image" where pipeline_id=i.pipeline_id;
 select coalesce(jsonb_agg(image_brief||jsonb_build_object('image_id',image_id,'asset_key',asset_key,'status',status,
   'generation_status',generation_status,'qa_status',qa_status,'file_status',file_status,'upload_status',upload_status,
   'storage_bucket',storage_bucket,'storage_path',storage_path,'sha256',sha256,'completed_at',completed_at) order by ordinal),'[]'::jsonb)
 into v_manifest from public."21_content_pipeline_image" where pipeline_id=i.pipeline_id;
 update public."18_content_pipeline" set image_manifest=v_manifest,
   stage=case when v_required>0 and v_done=v_required then 'IMAGE_READY' else 'VISUAL' end,updated_at=now()
 where pipeline_id=i.pipeline_id and ownership_state='CLAIMED';
 return jsonb_build_object('pipelineImageId',i.pipeline_image_id,'status','DONE','pipelineId',i.pipeline_id,
   'readyImageCount',v_done,'requiredImageCount',v_required,'contentStage',case when v_required>0 and v_done=v_required then 'IMAGE_READY' else 'VISUAL' end);
end $$;

create or replace function public.content_pipeline_fail_image_v1(
 p_pipeline_image_id bigint,p_pipeline_image_run_id bigint,p_claim_token uuid,p_failure_status text,
 p_failure_stage text,p_failure_code text,p_error text,p_retry_action text default null,
 p_generation_status text default null,p_qa_status text default null,p_file_status text default null,
 p_upload_status text default null,p_metadata jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare i public."21_content_pipeline_image"%rowtype; v_status text;
begin
 if p_failure_status not in ('RETRY','HOLD','BLOCKED','FAILED') then raise exception using errcode='22023',message='CONTENT_PIPELINE_INVALID_IMAGE_FAILURE_STATUS'; end if;
 v_status:=case when p_failure_status='FAILED' then 'RETRY' else p_failure_status end;
 select * into i from public."21_content_pipeline_image" where pipeline_image_id=p_pipeline_image_id for update;
 if not found then raise exception using errcode='P0002',message='CONTENT_PIPELINE_IMAGE_NOT_FOUND'; end if;
 if i.status<>'PROCESSING' or i.claim_token is distinct from p_claim_token then raise exception using errcode='40001',message='CONTENT_PIPELINE_IMAGE_CLAIM_CONFLICT'; end if;
 update public."21_content_pipeline_image" set status=v_status,retry_action=p_retry_action,
   generation_status=coalesce(p_generation_status,generation_status),qa_status=coalesce(p_qa_status,qa_status),
   file_status=coalesce(p_file_status,file_status),upload_status=coalesce(p_upload_status,upload_status),
   failure_stage=p_failure_stage,failure_code=p_failure_code,last_error=left(p_error,2000),
   claimed_by=null,claim_token=null,claimed_at=null,claim_expires_at=null,updated_at=now()
 where pipeline_image_id=p_pipeline_image_id returning * into i;
 update public."23_content_pipeline_image_run" set status=case when p_failure_status='FAILED' then 'FAILED' else p_failure_status end,
   completed_at=now(),failure_stage=p_failure_stage,failure_code=p_failure_code,error=left(p_error,2000),metadata=coalesce(p_metadata,'{}'::jsonb)
 where pipeline_image_run_id=p_pipeline_image_run_id and pipeline_image_id=p_pipeline_image_id and claim_token=p_claim_token and status='RUNNING';
 update public."18_content_pipeline" set stage='VISUAL',updated_at=now()
 where pipeline_id=i.pipeline_id and ownership_state='CLAIMED' and stage in ('DRAFTED','VISUAL');
 return jsonb_build_object('pipelineImageId',i.pipeline_image_id,'pipelineId',i.pipeline_id,'status',i.status,
   'retryAction',i.retry_action,'failureStage',i.failure_stage,'failureCode',i.failure_code);
end $$;

create or replace function public.content_pipeline_image_ready_guard_v1()
returns trigger language plpgsql security invoker set search_path='' as $$
declare v_required int; v_done int;
begin
 if new.stage='IMAGE_READY' and old.stage is distinct from 'IMAGE_READY' then
   select count(*),count(*) filter(where status='DONE') into v_required,v_done
   from public."21_content_pipeline_image" where pipeline_id=new.pipeline_id;
   if v_required=0 or v_done<>v_required then raise exception using errcode='40001',message='CONTENT_PIPELINE_IMAGES_NOT_COMPLETE'; end if;
 end if;
 return new;
end $$;
drop trigger if exists trg_content_pipeline_image_ready_guard on public."18_content_pipeline";
create trigger trg_content_pipeline_image_ready_guard before update of stage on public."18_content_pipeline"
for each row execute function public.content_pipeline_image_ready_guard_v1();

revoke all on function public.content_pipeline_sync_images_v1(bigint) from public,anon,authenticated;
revoke all on function public.content_pipeline_claim_image_v1(text) from public,anon,authenticated;
revoke all on function public.content_pipeline_complete_image_v1(bigint,bigint,uuid,text,text,text,text,text,text,text,jsonb) from public,anon,authenticated;
revoke all on function public.content_pipeline_fail_image_v1(bigint,bigint,uuid,text,text,text,text,text,text,text,text,text,jsonb) from public,anon,authenticated;
revoke all on function public.content_pipeline_image_ready_guard_v1() from public,anon,authenticated;
grant execute on function public.content_pipeline_sync_images_v1(bigint) to service_role;
grant execute on function public.content_pipeline_claim_image_v1(text) to service_role;
grant execute on function public.content_pipeline_complete_image_v1(bigint,bigint,uuid,text,text,text,text,text,text,text,jsonb) to service_role;
grant execute on function public.content_pipeline_fail_image_v1(bigint,bigint,uuid,text,text,text,text,text,text,text,text,text,jsonb) to service_role;
