create schema if not exists private;
create extension if not exists pg_cron with schema pg_catalog;

create table if not exists private.fitment_link_batch_run (
  run_id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  source_since timestamptz not null,
  tire_links_inserted integer not null default 0,
  battery_alias_links_inserted integer not null default 0,
  tire_positions_unresolved integer not null default 0,
  battery_codes_unresolved integer not null default 0,
  status text not null default 'RUNNING'
    check (status in ('RUNNING', 'PASS', 'PARTIAL', 'FAILED')),
  error_message text
);

revoke all on table private.fitment_link_batch_run from public, anon, authenticated;

create or replace function private.fitbike_speed_rating_rank(p_rating text)
returns integer
language sql
immutable
parallel safe
set search_path = ''
as $function$
  select case upper(regexp_replace(coalesce(p_rating, ''), '[^A-Z]', '', 'g'))
    when 'J' then 1
    when 'K' then 2
    when 'L' then 3
    when 'M' then 4
    when 'N' then 5
    when 'P' then 6
    when 'Q' then 7
    when 'R' then 8
    when 'S' then 9
    when 'T' then 10
    when 'U' then 11
    when 'H' then 12
    when 'V' then 13
    when 'ZR' then 14
    when 'W' then 14
    when 'Y' then 15
    else null
  end;
$function$;

create or replace function private.run_fitment_link_batch(
  p_since timestamptz default (now() - interval '2 days')
)
returns jsonb
language plpgsql
set search_path = ''
as $function$
declare
  v_run_id bigint;
  v_tire_inserted integer := 0;
  v_battery_inserted integer := 0;
  v_tire_unresolved integer := 0;
  v_battery_unresolved integer := 0;
begin
  -- Prevent a manual run and the scheduled run from overlapping.
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('fitbike-fitment-link-batch'));

  insert into private.fitment_link_batch_run (source_since)
  values (p_since)
  returning run_id into v_run_id;

  with target_years as (
    select y.*
    from public."03_bike_model_year" y
    where y.is_active = true
      and (y.created_at >= p_since or y.updated_at >= p_since)
  ),
  required_positions as (
    select
      y.bike_model_year_id,
      position.position_type,
      position.width,
      position.ratio,
      position.diameter,
      position.load_index,
      position.speed_index,
      position.tube_type
    from target_years y
    cross join lateral (
      values
        ('FRONT'::text, y.front_tire_width, y.front_tire_ratio, y.front_tire_diameter,
          y.front_tire_load_index, y.front_tire_speed_index, y.front_tire_tube_type),
        ('REAR'::text, y.rear_tire_width, y.rear_tire_ratio, y.rear_tire_diameter,
          y.rear_tire_load_index, y.rear_tire_speed_index, y.rear_tire_tube_type)
    ) position(position_type, width, ratio, diameter, load_index, speed_index, tube_type)
    where position.width is not null
      and position.ratio is not null
      and position.diameter is not null
  ),
  compatible_products as (
    select
      rp.bike_model_year_id,
      p.tire_product_id,
      rp.position_type,
      row_number() over (
        partition by rp.bike_model_year_id, rp.position_type
        order by p.tire_product_id
      )::integer as display_order
    from required_positions rp
    join public."04_tire_product" p
      on p.is_active = true
     and p.width = rp.width
     and p.ratio = rp.ratio
     and p.diameter = rp.diameter
     and (p.position_type = rp.position_type or p.position_type = 'BOTH')
     and (
       rp.tube_type is null
       or rp.tube_type = 'UNKNOWN'
       or p.tube_type = rp.tube_type
       or p.tube_type = 'TL_TT'
       or rp.tube_type = 'TL_TT'
     )
     and (rp.load_index is null or (p.load_index is not null and p.load_index >= rp.load_index))
     and (
       rp.speed_index is null
       or (
         p.speed_index is not null
         and private.fitbike_speed_rating_rank(p.speed_index) is not null
         and (
           private.fitbike_speed_rating_rank(rp.speed_index) is null
           or private.fitbike_speed_rating_rank(p.speed_index) >= private.fitbike_speed_rating_rank(rp.speed_index)
         )
       )
     )
  )
  insert into public."07_bike_model_year_tire_product" (
    bike_model_year_id,
    tire_product_id,
    position_type,
    match_type,
    display_order,
    is_active
  )
  select
    cp.bike_model_year_id,
    cp.tire_product_id,
    cp.position_type,
    'AUTO_SIZE_MATCH',
    cp.display_order,
    true
  from compatible_products cp
  on conflict (bike_model_year_id, tire_product_id, position_type) do nothing;

  get diagnostics v_tire_inserted = row_count;

  -- Battery products are connected by standard code rather than model-year ID.
  -- Only formatting-equivalent aliases of an already curated standard are copied;
  -- electrical or dimensional compatibility is never inferred automatically.
  with target_codes as (
    select distinct trim(y.battery_standard_code) as raw_code,
      upper(regexp_replace(trim(y.battery_standard_code), '[^A-Z0-9]', '', 'g')) as normalized_code
    from public."03_bike_model_year" y
    where y.is_active = true
      and (y.created_at >= p_since or y.updated_at >= p_since)
      and nullif(trim(y.battery_standard_code), '') is not null
  ),
  curated_matches as (
    select distinct
      tc.raw_code as battery_standard_code,
      existing.battery_product_id,
      existing.display_order
    from target_codes tc
    join public."08_battery_standard_product" existing
      on existing.is_active = true
     and upper(regexp_replace(trim(existing.battery_standard_code), '[^A-Z0-9]', '', 'g')) = tc.normalized_code
  )
  insert into public."08_battery_standard_product" (
    battery_standard_code,
    battery_product_id,
    match_type,
    display_order,
    is_active
  )
  select battery_standard_code, battery_product_id, 'VERIFIED', display_order, true
  from curated_matches
  on conflict (battery_standard_code, battery_product_id) do nothing;

  get diagnostics v_battery_inserted = row_count;

  with target_years as (
    select y.*
    from public."03_bike_model_year" y
    where y.is_active = true
      and (y.created_at >= p_since or y.updated_at >= p_since)
  ),
  required_positions as (
    select y.bike_model_year_id, position.position_type
    from target_years y
    cross join lateral (
      values
        ('FRONT'::text, y.front_tire_width, y.front_tire_ratio, y.front_tire_diameter),
        ('REAR'::text, y.rear_tire_width, y.rear_tire_ratio, y.rear_tire_diameter)
    ) position(position_type, width, ratio, diameter)
    where position.width is not null
      and position.ratio is not null
      and position.diameter is not null
  )
  select count(*)::integer
  into v_tire_unresolved
  from required_positions rp
  where not exists (
    select 1
    from public."07_bike_model_year_tire_product" link
    where link.bike_model_year_id = rp.bike_model_year_id
      and link.position_type = rp.position_type
      and link.is_active = true
  );

  select count(distinct trim(y.battery_standard_code))::integer
  into v_battery_unresolved
  from public."03_bike_model_year" y
  where y.is_active = true
    and (y.created_at >= p_since or y.updated_at >= p_since)
    and nullif(trim(y.battery_standard_code), '') is not null
    and not exists (
      select 1
      from public."08_battery_standard_product" link
      where link.is_active = true
        and upper(regexp_replace(trim(link.battery_standard_code), '[^A-Z0-9]', '', 'g')) =
            upper(regexp_replace(trim(y.battery_standard_code), '[^A-Z0-9]', '', 'g'))
    );

  update private.fitment_link_batch_run
  set completed_at = now(),
      tire_links_inserted = v_tire_inserted,
      battery_alias_links_inserted = v_battery_inserted,
      tire_positions_unresolved = v_tire_unresolved,
      battery_codes_unresolved = v_battery_unresolved,
      status = case
        when v_tire_unresolved > 0 or v_battery_unresolved > 0 then 'PARTIAL'
        else 'PASS'
      end
  where run_id = v_run_id;

  return jsonb_build_object(
    'run_id', v_run_id,
    'source_since', p_since,
    'tire_links_inserted', v_tire_inserted,
    'battery_alias_links_inserted', v_battery_inserted,
    'tire_positions_unresolved', v_tire_unresolved,
    'battery_codes_unresolved', v_battery_unresolved,
    'status', case
      when v_tire_unresolved > 0 or v_battery_unresolved > 0 then 'PARTIAL'
      else 'PASS'
    end
  );
exception
  when others then
    if v_run_id is not null then
      update private.fitment_link_batch_run
      set completed_at = now(), status = 'FAILED', error_message = sqlerrm
      where run_id = v_run_id;
    end if;
    raise;
end;
$function$;

revoke all on function private.fitbike_speed_rating_rank(text) from public, anon, authenticated;
revoke all on function private.run_fitment_link_batch(timestamptz) from public, anon, authenticated;

do $block$
declare
  v_job_id bigint;
begin
  select jobid into v_job_id
  from cron.job
  where jobname = 'fitbike-daily-fitment-link'
  limit 1;

  if v_job_id is not null then
    perform cron.unschedule(v_job_id);
  end if;

  -- pg_cron uses UTC. 15:00 UTC is 00:00 Asia/Seoul on the following day.
  perform cron.schedule(
    'fitbike-daily-fitment-link',
    '0 15 * * *',
    $cron$select private.run_fitment_link_batch();$cron$
  );
end;
$block$;
